### PR TITLE
Fixes #962: Integrate cumulative API to fetch metrics based skills

### LINKED ISSUE #962: The cumulative API integration for fetching skills based on metrics not integrated
**Actual Behaviour**
* The cumulative API integration for fetching skills based on metrics not integrated 

**Expected Behaviour**
* Reduces API calls by integration of the cumulative API

**Would you work on it?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #962 , #919 

Changes: [Add here what changes were made in this issue and if possible provide links.]
* Reduce API calls on homepage loading
* Integrate cumulative API to fetch metrics based skills

Surge Deployment Link: https://pr-963-fossasia-susi-skill-cms.surge.sh

**Dependent on server PR** - fossasia/susi_server#919

Screenshots for the change:
NA

### CODE REVIEW

**Comment by akshatnitd** [comment]
**Dependent on server PR** - fossasia/susi_server#919

**Comment by akshatnitd** [comment]
@anshumanv Currently, the usage_count of all skills are returned as 0. This is the reason, the order remains same. https://github.com/fossasia/susi_server/pull/904 will solve the issue.

**Comment by akshatnitd** [comment]
Yes, while merging, my changes were removed due to branch merge. Will send a fix for that.

**Comment by isuruAb** [comment]
@akshatnitd  please resolve the conflict

**Comment by akshatnitd** [comment]
@isuruAb Can you please review this now?

**Pull request merged**
