### PR TITLE
Fixes #728: Add ratings for skills over time

### LINKED ISSUE #728: Implement skill ratings over time received
**Actual Behaviour**
No such feature present

**Expected Behaviour**
Implement skill ratings over time as line chart to see how the skill is performing.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #728 

Changes: Added initial version of ratings over time line graph, making some modifications

Surge Deployment Link: https://pr-912-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
image

### CODE REVIEW

**Comment by anshumanv** [comment]
@Akshat-Jain @akshatnitd can you please restart the build since it throws segmentation fault, preview link will only be up once build passes.

**Comment by anshumanv** [comment]
The test passes locally - 
image

**Comment by Akshat-Jain** [comment]
@anshumanv I'm not sure why the Travis isn't passing, but the tests seem to pass locally as per the screenshot provided by you. However, can you please provide with a surge deployment link? Thanks :-)

**Comment by AnupKumarPanwar** [comment]
The deployment link is not working.

**Pull request closed without merging**
