### PR TITLE
Fixes #240 - Currently Editing shows blank field in modify skill page

### LINKED ISSUE #240: Currently Editing shows blank field in modify skill page
It should show the URL of the skill

**Screenshots of the issue**

screenshot from 2017-08-19 17 46 04

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #240 

Changes:

- Currently Editing now shows the skill route in modify skill page

Screenshots - 

screenshot from 2017-08-19 19 37 14

Link to deployment for testing:

http://parsimonious-development.surge.sh

Please review @dynamitechetan @saurabhjn76 @uday96 @madhavrathi @isuruAb

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by rishiraj824** [comment]
@mariobehling Fixed the conflicts. Please check.

**Comment by mariobehling** [comment]
Seems like there are several contradicting PRs. Once I merge one, the other one has conflicts. Please continue to resolve until PRs are merged.

**Comment by rishiraj824** [comment]
Sure I'll fix the conflicts again. @mariobehling

**Comment by mariobehling** [comment]
Travis is failing. Please check.

**Comment by rishiraj824** [comment]
@mariobehling Fixed travis.

**Pull request merged**
