### PR TITLE
Disable textbox when not required and clear all intervals while opening and closing the chatbot

### LINKED ISSUE #666: Various minor bugs in contact bot
**Bugs**

- [x] Avatar was removed in a previous PR. It's removed from contact bot as well. A default avatar should be provided for contact bot.
screen shot 2018-06-11 at 2 29 32 pm

- [x] Typing "Yes" or "No" doesn't work. Only clicking on option works. Both should work.
screen shot 2018-06-11 at 2 31 38 pm

- [x] Prevent a blank reply from user.
screen shot 2018-06-11 at 2 32 41 pm

- [x] Clicking on close button resets the bot but clicking on avatar simply closes it and doesn't reset the bot.

All of these need to be solved.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #666 

Changes:
- Disable textbox when not required
- clear all intervals while opening and closing the chatbot

Deployment Link: https://dns-404.github.io/

### CODE REVIEW

**Comment by DNS-404** [comment]
@anshumanv Done. Please review

**Comment by anshumanv** [comment]
Seems to work well initially but I'm seeing some weird behavior now, not sure what's causing this, can you please have more checks.
image

**Comment by DNS-404** [comment]
Closing the bot resets it.

**Comment by DNS-404** [comment]
@anshumanv @akshatnitd @Akshat-Jain @prateekiiest Fixed it. Please review.

**Comment by prateekiiest** [comment]
@DNS-404 did you update the demo-link?

**Comment by DNS-404** [comment]
Yes

**Comment by DNS-404** [comment]
The concept of contact bot from the beginning is that conversations will be reset when the bot is closed. What if you entered wrong name? or wrong email? or wrong message? What should you do then?
Well close the chatbot and do it again. That's why it's resetting on closing it is better.

**Comment by prateekiiest** [comment]
@DNS-404 agreed with you regarding the feature.

I guess if the email is invalid, then it can be caught as an exception as you have implemented that currently. But what if the user doesn't wish to specify his name.

May be his answer is "No I don't wish to answer my name"

**Comment by DNS-404** [comment]
@prateekiiest Your argument is valid but all of this can be done later. First priority is to get the first version of this up and running. This chatbot was created few days ago. There is a lot of scope for improvement. The backend for this isn't even merged yet. So investing a lot of time on improving its features while it isn't even in completely working state doesn't make much sense.

**Pull request merged**
