### PR TITLE
Fixes #323: Add sidebar on Home Screen

### LINKED ISSUE #323: Navigation sidebar for categories & language
**Actual Behaviour**
Presently, to view skills of a category, the user needs to select the category listed in a drop down and click submit button.

**Expected Behaviour**
Left Navigation sidebar with links to categories where the user can directly click to view the skills.

**Steps to reproduce it**
File: BrowseSkill.js
Changes: Refactor the modules, add helper functions, manage states for categories(groupValue) .

**Suggested Layout**
image

Please give your feedback on the layout.

**Would you like to work on the issue?**

Yes. I would like to work on the issue.

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #323 
Changes: 
* Added sidebar on home screen
* Made it responsive on mobile screen

Surge Deployment Link: https://pr-799-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
screenshot from 2018-06-20 12-52-24

### CODE REVIEW

**Comment by akshatnitd** [comment]
@DNS-404 Centered it. Looks good now.

@Akshat-Jain Nice catch. Fixed it!

**Comment by Akshat-Jain** [comment]
@akshatnitd Just a minor thing which also should be done. Currently, there is no way to find out which category we are in. Maybe keep the selected category highlighted in the left pane? Please think about this. Rest LGTM :+1:. Thanks :-)

**Comment by akshatnitd** [comment]
@Akshat-Jain I have tried highlighting the MenuItem using the inbuilt props, but that doesn't seem to work. I will fix the issue in a later PR and also make other styling changes. I think we can go ahead with the merge, if it is okay, as it is a blocker to other tasks for the Analytics team.

**Comment by Akshat-Jain** [comment]
@akshatnitd Okay, sounds good :+1:

**Pull request merged**
