### PR TITLE
Allow resizing of height of skill editor

### LINKED ISSUE #1430: Enhance skill editor to allow resizing of its height
**Expected Behaviour**

The SUSI skill editor should be enhanced to allow resizing of its height similar to the Github editor.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #1430 

Changes: Minor change in CSS to allow resizing of height of skill editor.

Surge Deployment Link: https://pr-1491-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

aug-08-2018 21-49-03

### CODE REVIEW

**Comment by love-san** [comment]
There are two scroll-bars here..
dns
Please look into this issue. Thanks.

**Comment by DNS-404** [comment]
I can not see it on my system `macOS High Sierra v10.13.4, Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)` as you can see in the screenshot I've provided above. Hence, this can be solved by anyone else in another issue.

**Comment by anshumanv** [comment]
Ah yes I think it's possible to keep one of those two for now, Ideally, we want to set the resize property for the inner scrollbar but that doesn't seem to happen.

**Comment by DNS-404** [comment]
I tested it on windows 10 (Google Chrome). I can see only one scroll bar. What should we do with this issue now? 😟 

abc

**Comment by mariobehling** [comment]
Merging it as wip.

**Pull request merged**
