### PR TITLE
Added Tooltip to Susi Launcher Button #1770

### LINKED ISSUE #1770: Adding Tooltip to Susi Launcher Button
**Actual Behaviour**
There is no tooltip present and the user doesn't know what is the usage of  button.

**Expected Behaviour**
Adding a tooltip.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

YEs/

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1770 

Changes:  Added Tooltip to Susi Launcher Button #1770

Surge Deployment Link: https://pr-1771-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
screenshot from 2019-01-02 19-46-07

### CODE REVIEW

**Comment by AakashMallik** [comment]
MUI lib provides tooltips on buttons. See if you can make use of them.

**Comment by sk9331657** [comment]
> MUI lib provides tooltips on buttons. See if you can make use of them.

@AakashMallik Actually, we are using self-made button and the tooltip in material UI requires the use of the material button to add that particular tooltip. So I have to add my own tooltip.

**Comment by sk9331657** [comment]
> @sk9331657 No one is stopping you from using their buttons btw. You are just using your own svg icon, which shall be no problem as far as I know.

@AakashMallik  I will surely check if that is possible without breaking styling of button.

**Comment by sk9331657** [comment]
@fragm3 Done that way.

**Pull request merged**
