### PR TITLE
Prefill the available code

### LINKED ISSUE #1422: Prefill create skill data
**Actual Behaviour**

The skill creator has to type all the information manually

**Expected Behaviour**

The available data like email, author name etc should be prefilled

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AnupKumarPanwar**
Fixes #1422 

Changes: 
1. Prefill the author name and autor_url in the skill code.
2. The author URL is the user's GitHub profile.

Surge Deployment Link: https://susi--cms.surge.sh

Screenshots for the change:
image

### CODE REVIEW

**Comment by mariobehling** [comment]
What if several authors edit the skill?

**Comment by AnupKumarPanwar** [comment]
@mariobehling Currently I'm following the current approach only, just automated the processing of filling the author name and author URL. The user can change them as well if needed.

**Comment by mariobehling** [comment]
@AnupKumarPanwar We need to be able to fill in several authors. The author that has made the most edits should be on top. Could you open an issue please and follow up if possible?

**Comment by AnupKumarPanwar** [comment]
@mariobehling I think we can add author and editors in the skill Metadata. Author would be the one whose initially creates the skill. What are your views?

**Pull request merged**
