### PR TITLE
Add Rating Popover to SkillCardList, CardGrid #1757,Add Tests#1786

### LINKED ISSUE #1757: Add functionality to Scrollcard Grid and Scrollcard List
**Actual Behaviour**

Not present

**Expected Behaviour**

For Scrollcard Grid, Add author name and tooltip on ratings to show the specific skill rating distribution and option to show all reviews.

For Scrollcard List, tooltip on ratings to show the specific skill rating distribution and option to show all reviews.

**Screenshot**

screenshot 2019-01-01 at 7 07 03 pm

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1757, #1786 

Changes:

- [x] For SkillCardList SkillCardGrid add, the tooltip(popover) on ratings to show the specific skill rating distribution and option to show all reviews.

- [x] Fix test folder structure for SkillRating and add test for SkillRating.js, SkillRatingPopover.js

Surge Deployment Link: https://pr-1787-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

screenshot 2019-01-09 at 4 38 56 am
screenshot 2019-01-09 at 4 39 20 am

### CODE REVIEW

**Comment by fragm3** [comment]
`2nd point` will be done with https://github.com/fossasia/susi_skill_cms/issues/1764 together.

**Comment by fragm3** [comment]
@akshatnitd @anshumanv please review

**Comment by fragm3** [comment]
@akshatnitd @anshumanv please review

**Comment by fragm3** [comment]
@akshatnitd the popover is working on the surge link.

GIF:
review-card-popover

**Comment by akshatnitd** [comment]
@fragm3 I still can't see it. 

@anshumanv @Akshat-Jain @AakashMallik Can you check and confirm on your end as well?

**Comment by fragm3** [comment]
@akshatnitd that's weird, I have tested it on Chrome as well as Firefox browser.

**Comment by AakashMallik** [comment]
@fragm3 @akshatnitd If I was supposed to see the pop up on hover, then nope, it ain't working. I just end up getting a tool tip that says "4.5 stars" and so on.

**Comment by fragm3** [comment]
On Mac:
popover

Please try clicking on the icon

**Comment by fragm3** [comment]
On Windows:
ezgif com-video-to-gif

**Comment by AakashMallik** [comment]
@akshatnitd @fragm3 Yup.. works... :+1:

**Comment by fragm3** [comment]
That's a relief, was wondering how it's not working

**Comment by anshumanv** [comment]
Thanks for gifs from all platforms. 😆

**Pull request merged**
