### PR TITLE
Feat: Image Upload is working from CreateSkill Component

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes Issue #187 

Link to deployment for testing:
http://weak-animal.surge.sh/
Screenshots for the change: 
image

### CODE REVIEW

**Comment by dynamitechetan** [comment]
@saurabhjn76 @DravitLochan @madhavrathi @rishiraj824  please review.

**Comment by hpdang** [comment]
Not working for test page for me.

**Comment by dynamitechetan** [comment]
It is working. When the homepage opens click the plus button. Then login and then create the skill. Upload the image and press save button. If the message says "accepted", go the skill browse page and see your skill there.

**Comment by hpdang** [comment]
@dynamitechetan The way it currently works does not provide a user with info if things are working or not. There should be a progress bar e.g. similar to Gmail when I upload something and once the image is uploaded it should show an icon. Please ensure things are implemented in a usable way right away in order to avoid lots of tiny follow-up issues.

**Comment by dynamitechetan** [comment]
@hpdang there is a progress bar. Please navigate to http://weak-animal.surge.sh/skillCreator
by clicking on the plus button on homepage. When the image uploads successfully there is a success message.
I already removed the model dropdown.
image

When you click on the save icon there is a linear progress bar. 
image

Finally, when skill upload is complete, a notification with success message also comes.
image

To check the upload is successful see this API response. I just created a skill named testingCMS.
image

**Comment by hpdang** [comment]
* png does not work
* jpg does not show upload bar for me.

Please see my earlier comments and help to make it easier for users.

**Comment by dynamitechetan** [comment]
Okay. I will move that upload button to the header.

**Comment by saurabhjn76** [comment]
@dynamitechetan It worked for me, @madhavrathi  @rishiraj824 Please try uploading the image and comment the issues you faced.

**Comment by dynamitechetan** [comment]
I tried uploading a JPG image, it works too. Even the loader shows up. Anyhow the loader and the type of the file uploaded are not related to each other.

**Comment by dynamitechetan** [comment]
Made the changes. Also updated the deployment URL. Please review again.
image
Only the image is not loaded here because the changes are not pushed to the SUSI Skill DATA repo from the server yet. But it is still committing the changes.
image

**Comment by mariobehling** [comment]
It is not working for me on Chromium/Chrome.

Please move the image feature to the left and show an icon of the image uploaded.

**Comment by mariobehling** [comment]
Also, I don't see this changed reflected on the skill editor. Why is there a difference between the skill editor and the create page? http://weak-animal.surge.sh/skillEditor

**Comment by mariobehling** [comment]
Clicking on any skill does and then using the edit button does not show the skill data and does not show the same editor. Why not?

**Comment by mariobehling** [comment]
@saurabhjn76 @DravitLochan @AliAyub007 Are you testing things in detail? Don't you see this?

**Comment by saurabhjn76** [comment]
@mariobehling Yes, I saw that skill data is not coming in editor,due to recent changes, it will be fixed by https://github.com/fossasia/susi_skill_cms/pull/199

**Comment by mariobehling** [comment]
#199 was just merged. Please update your deployment for testing. Thanks.

**Comment by dynamitechetan** [comment]
Done @mariobehling . I have updated the Deployment URL http://weak-animal.surge.sh/

**Comment by mariobehling** [comment]
Please follow the approach of Wikipedia: After clicking save show the skill page instead of showing "Your skill has been created."

**Comment by dynamitechetan** [comment]
@mariobehling after successful upload, redirection to skill page is working.

**Comment by mariobehling** [comment]
Awesome!

**Pull request merged**
