### PR TITLE
Fixes #1731: Helper files introduced for api calls; Redux integrated with login

### LINKED ISSUE #1731: Introduce helper ajax function and integrate login with redux
**Actual Behaviour**

No helper ajax file available to make ajax calls. Login is not linked to redux store as of now.

**Expected Behaviour**

Integrate login with redux store. Also introduce a helper file for making ajax calls.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #1731 
Changes: The changes I have made in this PR are:
* Introduced a helper ajax file, an api file, and two util files to help in api calls.
* Created new actionType APP_GET_LOGIN, actions and reducer.
* Integrated Login component with this new action.

Surge Deployment Link: https://pr-1732-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by AakashMallik** [comment]
@anshumanv I have introduced the helper files. Merging this would be helpful for other contributors trying to integrate redux actions and reducers. Let me know if some changes are required. 
Also could you please review this https://github.com/fossasia/susi_skill_cms/pull/1721, so that I can get the snackbars up and running again.

**Comment by AakashMallik** [comment]
@anshumanv Can this be reviewed/merged so that I can use the files added here to integrate other components into to the redux store..

**Comment by anshumanv** [comment]
Can we also remove the page reload on login as it's done in chat?

**Comment by AakashMallik** [comment]
@anshumanv I thought of doing that in this PR but it will be really tough to pull it off here in this PR. Would it be okay if I open another PR? And if this gets merged, it would make life really easy for redux integration. :sweat_smile:

**Pull request merged**
