### PR TITLE
Fixes #728: Add ratings for skills over time

### LINKED ISSUE #728: Implement skill ratings over time received
**Actual Behaviour**
No such feature present

**Expected Behaviour**
Implement skill ratings over time as line chart to see how the skill is performing.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #728 

Changes: Added initial version of ratings over time, line chart
Any issues related to responsiveness will be dealt afterwards.
Surge Deployment Link: http://messy-knowledge.surge.sh/
Screenshots for the change:
image

### CODE REVIEW

**Comment by anshumanv** [comment]
Investigating travis issue.

**Comment by anshumanv** [comment]
@Akshat-Jain @akshatnitd @AnupKumarPanwar it has been extremely sophisticated to make the travis pass, please see once

**Comment by anshumanv** [comment]
Making slight UI modifications.

**Comment by anshumanv** [comment]
@DNS-404 segmentations again and again, trying.

**Comment by anshumanv** [comment]
Updated the preview link - http://messy-knowledge.surge.sh/
Travis is still failing due to segmentation, can't do anything about it.

**Comment by AnupKumarPanwar** [comment]
@anshumanv I also faced the same codacy issue. Committing again in the PR may help.

**Comment by anshumanv** [comment]
It's fixed @AnupKumarPanwar

**Pull request merged**
