### PR TITLE
Fixes #212 , #229 - Added version control

### LINKED ISSUE #212: Make frontend for versioning
Show a list of commits and commit message on the skill page. On clicking on the commit the user can see the file at that commit ID. Then there must be a button so that admin can roll back to a commit id.
**API to get commits of a skill:** http://api.susi.ai/cms/getSkillHistory.json?model=general&group=Knowledge&language=en&skill=bitcoin
**API to get skill at a commit ID:** http://api.susi.ai/cms/getFileAtCommitID.json?model=general&group=Knowledge&language=en&skill=bitcoin&commitID=108631fdbd0b463c811bfb9ff3ff7ee1785c55fd

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #212 , #229 

**Changes:**
 - [x] Added a table showing commit history in skill page
 - [x] Show files for a selected commit
 - [x] Show difference between two selected commits
 - [x] Roll back to a selected commit
 - [x] Fixed setState before mount error for StaticAppBar

1. Select a skill
2. The commits are displayed as a table in skill page
3. Select one or 2 commits and click on the `view version` / `compare version` button.
4. If you wish to edit and push a previous version, click on `Undo`
5. Edit and click on `save`

Implemented in reference to Media Wiki - https://en.wikipedia.org/w/index.php?title=Tony_Hey&action=history

**Link to deployment for testing:** http://skillversioncontrol.surge.sh/

**Screenshots for the change:** 

diff

### CODE REVIEW

**Comment by uday96** [comment]
@dynamitechetan @saurabhjn76 @rishiraj824 @isuruAb @madhavrathi @mariobehling Please review

**Comment by mariobehling** [comment]
* Implement an automatic line break in the version view window. So, the user does not have to scroll to the right.
* In order to see a version, I have to click on it and then there is a "view button". Why? Just like Wikipedia offer a link to click on a version, please.
screenshot from 2017-08-17 09-53-13

**Comment by mariobehling** [comment]
Also the version history should not be on the skill page. Please implement a separate page "Versions" and add it on the skill page.

**Comment by mariobehling** [comment]
Pleasescreenshot from 2017-08-17 09-57-31

As this is increasing the height of the page, it now appears that the edit button is staying above the page, that the user scrolls up and down. This is not as expected. Please move the edit button to the top right - on the page itself and add a blue "Versions" button next to it.

**Comment by uday96** [comment]
- [ ]  Implement an automatic line break in the version view window. So, the user does not have to scroll to the right.
 - [ ]  Just like Wikipedia offer a link to click on a version
 - [ ] version history should not be on the skill page. Implement a separate page "Versions" and add it on the skill page.
 - [ ] move the edit button to the top right - on the page itself and add a blue "Versions" button next to it.

**Comment by uday96** [comment]
@mariobehling Please review. The check box functionality is not completely similar to that of wiki. Should it be changed to radio buttons like this?

**Comment by mariobehling** [comment]
Good job! Let's get this even closer to the flow on Wikipedia. At the moment we don't have revert functionalities here for example.

**Pull request merged**
