### PR TITLE
first steps for addition of skill Page with skilldetails

### PR DESCRIPTION
**Pull request by saurabhjn76**
progress on  issue #158 

Changes: 

- Added skill Page

- This is related to issue https://github.com/fossasia/susi_skill_data/issues/258.  Currently, the data is not shown, will get render once skills are updated with the new format.
- The baseurl used is [http://35.192.82.114/cms/getSkillMetadata.json](http://35.192.82.114/cms/getSkillMetadata.json), since [http://api.susi.ai/cms/getSkillMetadata.json](http://api.susi.ai/cms/getSkillMetadata.json) is giving 404 error.

Link to deployment for testing: http://garrulous-business.surge.sh/

Screenshots for the change: 
image

### CODE REVIEW

**Comment by mariobehling** [comment]
Do you have a test link?

**Comment by saurabhjn76** [comment]
@mariobehling : it's http://actually-pigs.surge.sh/

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
I am not seeing images and lots of other data on the skill page. So, as the issue is not fixed entirely, please change the description to "Addresses issue" instead of "fixes issue". This shows that this is work in progress.

**Comment by saurabhjn76** [comment]
[garrulous-business.surge.sh](garrulous-business.surge.sh)

**Comment by saurabhjn76** [comment]
@DravitLochan Done :+1:

**Comment by mariobehling** [comment]
Thanks! Good progress. Please follow up on outstanding points in the issue. Cheers.

**Pull request merged**
