### PR TITLE
Add navigation sidebar - fix #323

### LINKED ISSUE #323: Navigation sidebar for categories & language
**Actual Behaviour**
Presently, to view skills of a category, the user needs to select the category listed in a drop down and click submit button.

**Expected Behaviour**
Left Navigation sidebar with links to categories where the user can directly click to view the skills.

**Steps to reproduce it**
File: BrowseSkill.js
Changes: Refactor the modules, add helper functions, manage states for categories(groupValue) .

**Suggested Layout**
image

Please give your feedback on the layout.

**Would you like to work on the issue?**

Yes. I would like to work on the issue.

### PR DESCRIPTION
**Pull request by tstreamDOTh**
Fixes issue #323 

Changes:
-Add navigation sidebar
-Add responsiveness using CSS grid

Surge Deployment Link:  http://complex-disease.surge.sh/

Screenshots for the change: 
screen shot 2017-11-08 at 4 14 35 pm
screen shot 2017-11-10 at 5 24 05 pm

### CODE REVIEW

**Comment by mariobehling** [comment]
Test link not working for me and I am not convinced the approach works for a mobiles.

**Comment by mariobehling** [comment]
Would be great, if you could help to iterate step by step and help to improve this one here for example: https://github.com/fossasia/susi_skill_cms/issues/356

**Comment by tstreamDOTh** [comment]
@mariobehling Please try this http://complex-disease.surge.sh/ and give your feedback. For the mobile, the layout changes like this -
screen shot 2017-11-10 at 5 24 05 pm

**Comment by mariobehling** [comment]
@tstreamDOTh This is not entirely thought-through e.g. we should have a search functionality and below a filter functionality. Also you are taking out the top line entirely. Please iterate in smaller steps. Please add the top line back and we can get a search box on the top or something. We need to think this through more. Cheers.

**Comment by mariobehling** [comment]
Probably the iteration should be to put a top line for the general search of SUSI Skills first and then implement a way to filter skills on the left.

Top line similar to Susper for example.

screenshot from 2017-11-13 22-24-32

**Comment by tstreamDOTh** [comment]
@mariobehling Agreed totally. Even I was thinking on the same line. Can we open a separate issue for addressing the search feature? Will retain the top bar in it. The overall layout of proposed in this PR is inspired by Alexa skills website. I would like to work step by step to enhance skill cms portal. 
Please give your feedback.

**Comment by mariobehling** [comment]
> Will retain the top bar in it. 

Ok, please go ahead. Cheers.

**Comment by tstreamDOTh** [comment]
@mariobehling Should I add the search bar feature in this PR or in a separate one after this gets merged?

**Comment by mariobehling** [comment]
Please re-add the existing search bar. Please keep the design as is, simply add a sidebar. We can then think further changes through together.

**Comment by tstreamDOTh** [comment]
@mariobehling Should I close this PR then?

**Pull request closed without merging**
