### PR TITLE
Fixes #970: The category page shows 4 skills per row

### LINKED ISSUE #970: Only 3 skills show up on a row in the BrowseSkill component
**Actual Behaviour**
* Only 3 skills show up on a row in the BrowseSkill component

**Expected Behaviour**
* Show 4 skill cards in a row, by reducing padding.

**Screenshots of the issue**
screenshot from 2018-07-05 17-09-44

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #970 

Changes: [Add here what changes were made in this issue and if possible provide links.]
* The category page shows 4 skills per row

Surge Deployment Link: https://pr-979-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
screenshot from 2018-07-06 02-31-40

### CODE REVIEW

**Comment by akshatnitd** [comment]
@isuruAb The change is related to the no of cards per row in the Category page. Please try opening this route - [https://skills.susi.ai/category/All](https://skills.susi.ai/category/All). Thanks :)

**Comment by Akshat-Jain** [comment]
@akshatnitd Check this. Thanks :-)

screenshot_2018-07-06 10 16 33_adzhxk

**Comment by akshatnitd** [comment]
@Akshat-Jain Yes, the number of cards depend on the screen size and resolution. For me, it only shows 3 per row (as shown in the screenshot), So, the PR is an UI fix to display 4 cards for all standards screens. Also, the wrap property of flex is used, that is the reason it shows 4 for you as of now.

**Comment by Akshat-Jain** [comment]
@akshatnitd I think that you should make the changes only for smaller screen sizes. Because in the deployment link, the cards are now very closely packed to each other on my screen.

screenshot_2018-07-06 10 26 19_2e0lxe
screenshot_2018-07-06 10 27 00_t1rxm4

**Pull request merged**
