### PR TITLE
Fixes #167 - Added favicon and fixed topbar height

### LINKED ISSUE #167: Follow position of logo and height/design of top bar of web chat
The height, position, size of the logo is not following the webchat. Please adhere to it.

.ico is also not same as web chat. Please adhere to it!

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #167 

**Changes:**
 - Added favicon
 - Fixed top bar height similar to webchat
 - Fixed width of SUSI logo similar to webchat
 - Changed Login Signup buttons colors to match webchat
 - Changed Login dialog style similar to webchat

**Link to deployment for testing:** http://topbar.surge.sh/

**Screenshots for the change:**

log

### CODE REVIEW

**Comment by uday96** [comment]
@hpdang @saurabhjn76 @dynamitechetan Please review. Should the SUSI logo remain on the left or be centered?

**Comment by mariobehling** [comment]
Please align SUSI logo and position in the same way as on the web chat. Also make the size and everything in the same way.

**Comment by mariobehling** [comment]
Also implement the same browser ico as the web chat.

**Comment by mariobehling** [comment]
* Plus, I see that the right side dropdown buttons have a different position too.
* The scrollbar is behind the top blue app
screenshot from 2017-07-31 17-40-08

* The scroll bar doesn't disappear in the same way as the overview page

-> Just make it in the same way as the web chat app e.g. the overview page.

**Comment by uday96** [comment]
@mariobehling Yes. I'm working on it. Will update the PR once its done.

**Comment by uday96** [comment]
**Changes :** 
 - Made Static App bar similar to webchat overview page with the scroll effect

@mariobehling Please review.

**Comment by mariobehling** [comment]
You forgot my comment here: https://github.com/fossasia/susi_skill_cms/issues/167#issuecomment-319095817

**Comment by uday96** [comment]
@mariobehling Sorry. I missed it. Have aligned the logo to the left and the top bar also works in the same way like webchat overview page. Please take a look

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
