### PR TITLE
Fixes: #231 partially - implemented child routing for Skills

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #231

Changes: change routings of skills and now users can access skills directly through the link.

Link to deployment for testing: http://isuruab.surge.sh/

### CODE REVIEW

**Comment by isuruAb** [comment]
@uday96  thank you @uday96. please review this again. http://isuruab.surge.sh/ 👍

**Comment by mariobehling** [comment]
@isuruAb Is the following format possible?
`/Knowledge/day_in_history/edit/en`

**Comment by isuruAb** [comment]
@mariobehling  yes I will change it asap

**Comment by isuruAb** [comment]
@mariobehling  I arrange the URL structure like this.
edit mode: 
/Knowledge/day_in_history/edit/en

skill page:
/skill/Knowledge/day_in_history/en

**Comment by isuruAb** [comment]
@mariobehling  please check this again.
I have changed URL structure into this.
http://isuruab.surge.sh/Knowledge/capital/en
http://isuruab.surge.sh/Knowledge/capital/edit/en

**Comment by mariobehling** [comment]
Very good. Thanks!

**Pull request merged**
