### PR TITLE
Create a section to display general metrics to users 

### LINKED ISSUE #459: Create a section to display general metrics to users
**Actual Behaviour**
Currently, there is no such section as such.

**Expected Behaviour**
There should be a section that display the general metrics like Top Skills, Latest Skills and Top Rated Skills.

**Would you like to work on the issue?**
Yes, I would like to work on it. It can be done after fossasia/susi_server#725

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #459 
Changes: 
* Add new route /explore for Metrics page

Surge Deployment Link: https://pr-505-fossasia-susi-sill-cms.surge.sh

### CODE REVIEW

**Comment by anshumanv** [comment]
https://pr-505-fossasia-susi-sill-cms.surge.sh/explore

@AnupKumarPanwar

**Comment by anshumanv** [comment]
We can even add a MenuItem in the dropdown.

**Comment by AnupKumarPanwar** [comment]
image

@akshatnitd Is the page currently empty or its not loading on my browser?

**Comment by akshatnitd** [comment]
@AnupKumarPanwar It is empty currently. i have added [WIP] on PR title. This issue will be solved via multiple commits.

**Comment by anshumanv** [comment]
@akshatnitd please resolve conflicts so this can be merged and we further start populating the section.

**Comment by mariobehling** [comment]
Please update to `/dashboard` as discussed elsewhere.

**Comment by akshatnitd** [comment]
@mariobehling This section is aimed to show something similar to this link - https://assistant.google.com/explore/. And I have used the route `/explore`, which is used by google and sounds more apt for what we are trying to show

**Comment by mariobehling** [comment]
@akshatnitd Looking at this more closely now, it does not make sense. What you think should be the explore page, we try to achieve on our start page similar to https://assistant.google.com/explore/. Please delete this route and links. It cannot be reverted automatically, please take care of it manually.

**Comment by anshumanv** [comment]
@mariobehling the idea while implementing this page was to, show top 5 skill cards in categories like top rated, top used, trending etc. We can remove it no problem.

If we delete this page, can you suggest a more suitable place where the skill cards for top rated etc should be displayed, please?

**Comment by akshatnitd** [comment]
@mariobehling We are also looking to implement something similar to the the  https://assistant.google.com/explore/ page. But for this, we thought of making the changes first on the `/explore` page and then replacing the index route(`/`) to `/explore`, so that the CMS home page doesn't seem to be incomplete for now.  If you suggest, I can revert back the changes manually.

**Pull request merged**
