### PR TITLE
Fixes #1125: Show supported languages for a skill

### LINKED ISSUE #1125: Add languages supported by a Skill
**Actual Behaviour**
* Not present

**Expected Behaviour**
* Add languages supported by a Skill.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #1125

Changes: [Add here what changes were made in this issue and if possible provide links.]
* Show supported languages for a skill

Surge Deployment Link: https://pr-1347-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
deepinscreenshot_select-area_20180728140946

### CODE REVIEW

**Comment by fragm3** [comment]
Update surge link

**Comment by akshatnitd** [comment]
@fragm3 Updated the link.

**Comment by fragm3** [comment]
The language part is already there. Not sure about this, since both things show same stuff.

**Comment by akshatnitd** [comment]
@fragm3 It will soon start to make more sense, when we have same skill in different languages.

**Pull request merged**
