### PR TITLE
[WIP]initial setup for SUSI admin panel

### LINKED ISSUE #186: For Admin Users show menu item "Admin"
Users List was implemented in the dropdown menu for all users. It should not be there.

Please implement a menu item "Admin" below the settings item. Only show this point for admin users! Do not show this menu item for anonymous or logged in users.

On the page on the route `/admin` show tabs for `users` and `permissions` similar to this one (but using the design of the skills cms).

### PR DESCRIPTION
**Pull request by DravitLochan**
first step #186 
For Susi admin panel, defined admin files and route. on login, stored base user role. On logout, deleted it. 
removed option for list user and added option for 'admin' which is visible iff user is an admin.
surge deployment link : http://susi-admin.surge.sh/
w/o login : 
without_login
with admin login : 
with_admin
with user login : 
without_admin

### CODE REVIEW

**Comment by DravitLochan** [comment]
@saurabhjn76 @dynamitechetan @madhavrathi @uday96 @rishiraj824 @isuruAb Please review.

**Comment by mariobehling** [comment]
Where are screenshots? I don't have that option.

**Comment by DravitLochan** [comment]
@mariobehling Added the screenshots. Please use http://susi-admin.surge.sh/ to test it. @Orbiter Please test it.

**Comment by saurabhjn76** [comment]
@DravitLochan Locally works fine

**Comment by mariobehling** [comment]
What is the feature that should be seen working here? This is not solving an issue? Where is the first tab for user listings? Please make substantial commits that implement a feature.

**Comment by DravitLochan** [comment]
@mariobehling This was the first step towards admin panel which was to add "admin" option only for admins. Anyway, I am nearly done with rest of the work and now admin panel looks something like this. Will add more commits to complete it. Please suggest if you think any changes are required. 
screenshot from 2017-08-09 20-30-28

**Comment by mariobehling** [comment]
Please ensure you implement clean styles, avoid new colors and follow the tab approach of open event.

Tabs in Open Event Admin panel.
screenshot from 2017-08-09 17-58-54

**Comment by DravitLochan** [comment]
@mariobehling Not sure how this type of tabs (non-material based) will look with other things implemented in material.

**Comment by mariobehling** [comment]
This is just an example. Of course use material design.

**Comment by DravitLochan** [comment]
I am already working on it. Please merge this as a WIP as it also implements a feature-  to add "admin" option only for admins. If a non admin user tries skills.susi.ai/admin-panel, it would give them a notification that they are not admins till now.

**Comment by mariobehling** [comment]
Please do read issues more carefully and implement features without too many small steps as work in progress. Provide a substantial improvement within a day and open PRs. The admin dashboard needs to go to `/admin` and include tabs. Please finalize this issue. Why is it taking so long?

**Comment by DravitLochan** [comment]
There were quite many changes on the server in recent times which lead to delays.

**Comment by DravitLochan** [comment]
Should I finalize with this type of tabs? Will try to match the theme as far as possible.
screenshot from 2017-08-11 13-02-22

**Comment by mariobehling** [comment]
I am not seeing the admin point in the dropdown. I should be in the admin group.

**Comment by DravitLochan** [comment]
@mariobehling Updated the link. You can also see the progress and comment if anything needs to be changed.

**Comment by mariobehling** [comment]
Travis is not working yet here.
I don't see an admin tab for me.

**Comment by DravitLochan** [comment]
re login. This should work. This pr is to just show my progress. I will open a new pr as soon as this is complete. kindly ignore travis for now

**Comment by mariobehling** [comment]
Follow the alignment as on the start page
* heading 1: Same indent as white top menu 
* tabs area: Same as the width of the skills on frontpage
* Other: Avoid effects, e.g. left and right of tabs. No effects, please. Keep it simple and clean.

screenshot from 2017-08-12 13-09-43

**Comment by mariobehling** [comment]
@DravitLochan Hope you can finalize this issue quickly.

**Comment by DravitLochan** [comment]
@mariobehling Yes. I am working on it only. No other commitment right now. I am implementing the feature with the assumption that [this](https://github.com/fossasia/susi_server/pull/491) gets merged.

**Comment by DravitLochan** [comment]
@mariobehling Please see the deployment link once. I have tried to meet the open events tab style as far as it was supported by material UI. If approved, I'll clean up the code, close this pr and open a new one. Please see that you will not be able to see the data yet as data rendering is left. If you have issues accessing /admin, kindly re login.

**Pull request closed without merging**
