### PR TITLE
Fixes #787: Display feedback timestamp

### LINKED ISSUE #787: Show feedback timestamp on individual feedbacks
**Actual Behaviour**
Timestamp is absent

**Expected Behaviour**
It should be present.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #787 

Changes: Added timestamp on skill feedback

Surge Deployment Link: https://pr-797-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
image

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
I think the alignment of timestamp is good on left side, just format the timestamp.
image

**Comment by anshumanv** [comment]
@Akshat-Jain @akshatnitd @AnupKumarPanwar formatted the date and made some ui changes, looks closer to the play store now.

**Comment by akshatnitd** [comment]
@anshumanv Yes, maybe then you can just format the timestamp and style it properly, as all the elements seem to be very close. Try changing the sizing, as well as the colors.

**Comment by anshumanv** [comment]
@akshatnitd check the updated screenshot, updated the color and timestamp. What else do you suggest we should incorporate. :thinking:

**Pull request merged**
