### PR TITLE
Added Speed Dial Layout for Edit Skill and Version button

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes issue #258 
Added speed dial fab button for edit skill and version buttons on Skill page.
Link to deployment for testing: http://nonstop-pickle.surge.sh
Screenshots for the change: 
image

### CODE REVIEW

**Comment by mariobehling** [comment]
While it looks good, it does not add functionality and rather increases the number of clicks. Instead of adding more clicks, it would be great if you could simply exchange the button "versions" with the one you provide here, but leave the location as is for now.

**Comment by mariobehling** [comment]
Could you keep this more simple for now, please? Please show it on the top and on scroll over show tool tip for the button you are scrolling over.

29532620-8c8430e2-86cb-11e7-9a68-df6f636de7bb

**Comment by dynamitechetan** [comment]
Okay.

**Comment by mariobehling** [comment]
There will be more information into sections below in future e.g. for ratings and user comments. The design you proposed makes sense for the moment, but it would not make sense entirely once we expand with additional sections.

**Comment by dynamitechetan** [comment]
@mariobehling  made the changes
image

**Comment by mariobehling** [comment]
@dynamitechetan Not seeing the tool infos on scroll overs.

**Comment by dynamitechetan** [comment]
@mariobehling added the tooltip now

**Comment by mariobehling** [comment]
The tooltip is slightly delayed. Please make it immediate.

**Comment by dynamitechetan** [comment]
@mariobehling please check again.

**Pull request merged**
