### PR TITLE
Fix Preview Toggle Button

### LINKED ISSUE #1763: Fixed Toggle Button In Preview Section
**Actual Behaviour**
Toggle Button is hidden.

**Expected Behaviour**

**Steps to reproduce it**
Test the bug here https://skills.susi.ai/botbuilder/botwizard.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes
screenshot from 2019-01-01 18-55-53

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1763 

Changes: Fix Preview Toggle Button Like in Badgeyay

Surge Deployment Link: https://pr-1765-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

ezgif com-video-to-gif 8

### CODE REVIEW

**Comment by sk9331657** [comment]
@DNS-404  Ok I got it. But it will be better to Keep the button up. Have a look at this. http://badgeyay.com/create-badges I have implemented similar toggler here.

**Comment by sk9331657** [comment]
@mariobehling @akshatnitd  I have shifted the toggle button above the susi frame as it will be better for the user to use it. Please review.

**Comment by sk9331657** [comment]
@DNS-404 Please review.

**Comment by AakashMallik** [comment]
@sk9331657 The two designs are not comparable and I think the button was better placed before unless you can justify some logic that we might be missing.

**Comment by akshatnitd** [comment]
This PR is not required. Hence, closing it. Please look to solve already open issues.

**Pull request closed without merging**
