### PR TITLE
updated skillPage endpoint as per server changes

### LINKED ISSUE #198: SUSI skill cms is not working due latest server changes
Will fix it

### PR DESCRIPTION
**Pull request by saurabhjn76**
Fixes #198 , #200 

Changes: Updated cms as per changes in susi_server cms endpoints

Link to deployment for testing: http://susi_skill_cms.surge.sh/

Screenshots for the change: 
image

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Looks good except the console error.

**Comment by madhavrathi** [comment]
@saurabhjn76 I have fixed the issue in my PR: https://github.com/fossasia/susi_skill_cms/pull/197
Please have a look.
Thanks

**Comment by hpdang** [comment]
Please resolve merge conflicts.

**Comment by saurabhjn76** [comment]
@hpdang Please review

**Comment by hpdang** [comment]
CMS is working already again. What improvements are additionally is this PR for now?

**Comment by saurabhjn76** [comment]
@hpdang SkillPage is working now

**Pull request merged**
