### PR TITLE
Add icons for conversation view

### PR DESCRIPTION
**Pull request by DNS-404**
Partially solves issue #576 

Changes: Added icons. They're in static form currently.
I could do it dynamically(add using text box) in this PR only but I'm trying to avoid using jQuery which I used before. I'll try to do it with react itself.

Next step: Add them dynamically and add delete option.

Surge Deployment Link: https://pr-727-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

screen shot 2018-06-15 at 3 25 16 pm

### CODE REVIEW

**Comment by DNS-404** [comment]
@akshatnitd  Yes exactly, just like @hkedia321 said, we're using android icon in tree view as well and I couldn't find any other appropriate icon for a "bot".

**Comment by DNS-404** [comment]
@akshatnitd Can these icons be used as it is? I mean do I have to provide some license for using them? 🤔

**Comment by akshatnitd** [comment]
@DNS-404 Instead of adding the script to the index.html file, I suggest keeping the icon in the static assets and then importing it from there.

**Comment by anshumanv** [comment]
Use something like 
`import image name from 'image path'`

**Pull request merged**
