### PR TITLE
Fixes #204 Made skill cards identical

### LINKED ISSUE #204: Make the skill display cards of same size
**Actual Behaviour**

All cards of skill display are not identical
**Expected Behaviour**

They should be identical in height and width.

**Screenshots of the issue**

cms_issue

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixed #204 Made skill cards identical and did some code refactoring.

Link to deployment for testing: http://susiskillmadhav.surge.sh/

Screenshots for the change: 
cms_issue_fix
@dynamitechetan @DravitLochan @saurabhjn76 @rishiraj824 Please Review
Thanks

### CODE REVIEW

**Comment by madhavrathi** [comment]
mariobro
I have handled this for all the descriptions. Please review: http://susiskillmadhav.surge.sh/

**Comment by mariobehling** [comment]
@madhavrathi Can you make use of the full 3rd line, please?

**Comment by madhavrathi** [comment]
@mariobehling Since this is a card we are using to display information, I cannot really use the concept of lines, I have counted the words in a string, then if it is more than 100, then I have shortened it. 100 is the number which will fit in three lines.I guess this implementation will work. Should I increase the word count?

**Comment by mariobehling** [comment]
@madhavrathi Instead of words, please use characters including spaces.

**Comment by madhavrathi** [comment]
@mariobehling Made the requested changes. Screenshot : 
newbro

**Comment by mariobehling** [comment]
Good job.

**Pull request merged**
