### PR TITLE
Redesign UI of chatbot

### LINKED ISSUE #502: Odd positioning of SUSI logo in the susi plugin
**Actual Behaviour**

Currently, when I am integrating SUSI plugin on my website, the SUSI logo is in an odd place

**Expected Behaviour**

To improve the positioning of the SUSI logo

**Screenshots of the issue**
screen shot 2018-05-25 at 3 19 58 pm

**Would you like to work on the issue?**
This issue can be assigned to anyone

### LINKED ISSUE #503: Redesign the UI of chatbot plugin
**Actual Behaviour**

Currently there are a lot of issues with UI of chatbot.

**Expected Behaviour**

All these issues need to be solved. Along with this I'll improve the overall UI of chatbot.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #503 
Fixes #502 

Changes: Completely redesigned the UI of chatbot. Now it's much better. This solves all the small bugs people were facing before with UI. (Example - #502 )

Link for testing: https://dns-404.github.io/

Screenshots for the change:

**Initial icon:**
Before -
screen shot 2018-05-26 at 3 06 03 pm

After -
screen shot 2018-05-26 at 3 01 28 pm

**Chatbox:**

Before -
screen shot 2018-05-26 at 3 06 20 pm

After -
screen shot 2018-05-26 at 3 01 44 pm

### CODE REVIEW

**Comment by DNS-404** [comment]
@mariobehling @hkedia321 @AliAyub007 @anshumanv @akshatnitd 
Please review.

**Comment by DNS-404** [comment]
For avatar of SUSI, I used the `favicon.ico` image. Is it fine like this or should I use some other image?

**Comment by DNS-404** [comment]
Codacy issues are for removing `!important` from CSS only.

**Comment by DNS-404** [comment]
Codacy is asking me to remove `!important`. I can't remove it from these three CSS properties. I removed it from all the other.

**Comment by anshumanv** [comment]
We generally don't use `!important` and it's not a good practice to use it anymore :sweat_smile:

**Comment by anshumanv** [comment]
Find some other workaround to get the desired output

**Comment by DNS-404** [comment]
I know it's not a good practice but I couldn't find any other way to do it. 😟
Fine, I'll try to find some other way.

**Comment by DNS-404** [comment]
- Increased width from `300px` to `350px`
- Removed `!important` tags. Should solve Codacy errors.

**Comment by DNS-404** [comment]
@Akshat-Jain @PrP-11 @stealthanthrax Please review

**Comment by DNS-404** [comment]
@hkedia321 I was facing some problem in "typing" animation. Let's get this merged first. We can add that later on. 😅

**Comment by DNS-404** [comment]
Changed the Avatar. Check it out here - https://dns-404.github.io/

**Comment by DNS-404** [comment]
@dynamitechetan @saurabhjn76 Please review

**Comment by DNS-404** [comment]
@madhavrathi I fixed it. Please have a look. https://dns-404.github.io/ 😃

**Pull request merged**
