### PR TITLE
Add My Bots section to Botbuilder, option to add name of bot and save it

### LINKED ISSUE #744: Web bot should be saved after setting a name
**Actual Behaviour**

No option to set name for a web bot or save it. No option for creating multiple bots.

**Expected Behaviour**

- Dashboard needs to be modified to have a column of "My bots". This will show all the bots created by user in cards form and will have an option to create a new bot as well.
This will be done similar to how it's done in [landbot.io](landbot.io)
screen shot 2018-06-19 at 4 01 53 pm

- A name for each new bot will be asked as a necessary field. No bot will be saved without a name.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Partially fixes issue #744 
This solves most of the frontend part. Backend will be done in issue https://github.com/fossasia/susi_server/issues/859.

Changes: 
- Added "My Bots" Section to Botbuilder.
- Added field for name of the bot.
- Button to save and deploy the bot. This will work only if a name field isn't empty.

Surge Deployment Link: http://abounding-crush.surge.sh/

Screenshots for the change:

Botbuilder -
screen shot 2018-06-20 at 1 58 59 am

Botwizard-
screen shot 2018-06-20 at 1 59 21 am

Save doesn't work if field is empty-
jun-20-2018 02-03-07

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by DNS-404** [comment]
@mariobehling Resolved conflicts and added some sample bot examples which shows how bots will appear after a user saves it. Saving a bot will work once it's implemented in the server.
Screenshot -
screen shot 2018-06-20 at 7 51 28 pm

**Comment by hkedia321** [comment]
@DNS-404 In the preview link, the bot templates and the sample bots are not visible. Please check.
image

**Comment by DNS-404** [comment]
@hkedia321 I've provided a new link. Thanks for pointing that out!

**Pull request merged**
