### PR TITLE
Fixed bugs while changing theme for logged in Users

### LINKED ISSUE #568: Bugs in theme settings need to be fixed
**Actual Behaviour**

Currently, the theme settings have a few bugs.

**Expected Behaviour**

The bugs need to be fixed.

**Steps to reproduce it**

Go to https://skills.susi.ai and login. Then change theme from Light to Dark. Now again try changing theme from Dark to Light. You'll see that it doesn't work as expected as the Light option is already selected and it gives you the option to switch to Dark theme only.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #568 

Changes: Fixed the bugs while changing theme for logged in Users

Surge Deployment Link: https://pr-570-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
@stealthanthrax Please check the issue. I've updated it with a GIF illustrating the issue. Thanks :-)

**Comment by mariobehling** [comment]
Please take out the theme feature here in the skills CMS entirely. It does not bring us more users. Refer here for full explanation: https://github.com/fossasia/susi_skill_cms/issues/568#issuecomment-394180123

**Comment by Akshat-Jain** [comment]
@mariobehling Okay, I'm on it.

**Comment by Akshat-Jain** [comment]
@mariobehling Created an issue for removing Theme feature from Skill CMS (https://github.com/fossasia/susi_skill_cms/issues/575). Hence, closing this PR as this is no longer required.

**Pull request closed without merging**
