### PR TITLE
Fixed #417: Remove inconsistent link to docs

### LINKED ISSUE #417: Broken link in docs
**Actual Behaviour**
Setting up permanent skills doc in https://github.com/fossasia/susi_skill_cms/blob/master/docs/Skill_Tutorial.md#what-you-have-to-do is broken

**Expected Behaviour**
Fix the broken link.

**Would you like to work on the issue?**
Will send a quick fix.

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #417 

Changes: Removed inconsistent link

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Hi @anshumanv . SUSI Skill CMS was created so that new skills can be created from this CMS. We don't want PRs at Skill Data anymore. SUSI Skill data is just a place where skills are stored. We want it to be like Wikipedia, where anyone can create or edit any skill.
@saurabhjn76 Views?

**Comment by saurabhjn76** [comment]
@dynamitechetan rightly said. All new skills should be added from Skill CMS. @anshumanv Please update the docs accordingly.

**Comment by madhavrathi** [comment]
@dynamitechetan totally agreed.

**Comment by anshumanv** [comment]
@dynamitechetan @saurabhjn76 @AnupKumarPanwar thanks for that, fixed. :+1:

**Pull request merged**
