### PR TITLE
Fixes #859: Make the list view of the skill cards add toggle between views

### LINKED ISSUE #859: Redesign the Category Wise Skill Page
**Actual Behaviour**
* It currently uses BrowseSkill component.

**Expected Behaviour**
* The component needs to be implemented afresh and the UI should look like this - [Link](https://www.amazon.com/s/ref=lp_13727921011_nr_n_0?fst=as%3Aoff&rh=n%3A13727921011%2Cn%3A%2113727922011%2Cn%3A14284819011&bbn=13727922011&ie=UTF8&qid=1529866174&rnid=13727922011)

- [x] Make the sidebar as shown on the link.
- [ ] Design the Cards as shown on the link.
- [x] Make the page layout as shown on the link.

**Would you like to work on the issue?**
@anshumanv @AnupKumarPanwar and I would take this up.
Please comment on which subparts you would be working on.

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #859 

Changes: [Add here what changes were made in this issue and if possible provide links.]
* Redesign the skill cards and make the design extensible.

Surge Deployment Link: https://pr-1063-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

peek 2018-07-12 17-11

### CODE REVIEW

**Comment by akshatnitd** [comment]
@Akshat-Jain Made the changes.

**Comment by AnupKumarPanwar** [comment]
@akshatnitd I agree with @mariobehling . There should be an option to change the view as I personally like the SUSI grids more than the Alexa skill lists.

**Comment by akshatnitd** [comment]
@mariobehling @AnupKumarPanwar @anshumanv I have made the changes as requested. Please review. I will be working on the mobile view of the List View in a new PR.

**Comment by akshatnitd** [comment]
@mariobehling Made the suggested changes.

**Pull request merged**
