### PR TITLE
Make skill editor behaviour similar to github's editor

### LINKED ISSUE #1236: Implement "Code box" in Skills and Botbuilder similar to Github
The entry box in Github can be used as an example for the code entry. Please implement it more similarly. Ensure the scroll bar on the right only shows up if there are more lines of code than the height of the screen.

### LINKED ISSUE #1288: Improve Skill editor's UI to match with github
**Actual Behaviour**

- the background color remains white when the user focuses on the editor. User is unable to differentiate the area between the editor and outside.
- Scrollbar appears even when there is no content to scroll.
image

**Expected Behaviour**

- the background color should become white when user focuses on the editor and remain grey otherwise, similar to github's editor.
- the scrollbar should appear only if there is content to scroll.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes #1236 
Fixes #1288

Changes: 
- make the default background color to grey (`#fafbfc`) color, same as github's.
- change the background color to white when focused.
- put grey border around the editor, same as github's.
- change the border's color to blue when focused, same as github's.
- remove scrollbar when there is nothing to scroll.

These changes are applied for everywhere where the editor is appearing (botbuilder, public skill, edit skill, etc).

Note: I have to use `!important` to overwrite the default styling of the Ace editor, which is coming from it's own css file.

Surge Deployment Link: https://pr-1374-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
skill editor github gif

### CODE REVIEW

**Comment by hkedia321** [comment]
@akshatnitd @stealthanthrax @DNS-404 Resolved conflicts. Please review.

**Comment by hkedia321** [comment]
Travis was failing due to use of `!important`. This is required to overwrite the default background color of the Ace editor. I added the comment `/* csslint allow: known-properties, important */` to allow the use of `!important` in the two lines. 
@Akshat-Jain @DNS-404 @akshatnitd Please review.

**Comment by akshatnitd** [comment]
Good work! But, I feel the background color, when the edit area isn't on focus, gives a feel that the area is disabled. Since, editing is always possible on the editor, it should always have a white background IMO.

**Comment by DNS-404** [comment]
@akshatnitd Look at the comment box on this PR (Github comment box), it too is greyish when not in focus. The editor is similar. So it looks good to me. 🤔

**Pull request merged**
