### PR TITLE
Moving Auth to Parent component [Fully functional]

### LINKED ISSUE #1727: Move Auth component to Parent component.
**Actual Behaviour**

Currently, Auth components are being rendered by the StaticAppBar.

**Expected Behaviour**

Ideally, it should be rendered by the parent component index.js

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #1727 

Changes: The changes I have made are: 
- [x] Delete the Auth/index.js
- [x] Declare states and function to render Login, Signup and ForgotPassword in the Parent component ( index.js )
- [x] Restructure the Dialogs ( Login, Signup and ForgotPassword ) to work well with these changes.
- [x] Use snackbar declared in Parent to display errors.
- [x] Propagate the functions declared in index.js to all the route components.

Surge Deployment Link: https://pr-1737-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by AakashMallik** [comment]
@anshumanv After this PR is finished we shall be able to deploy the login whenever needed and it will not be in the control of staticAppBar only, so if user is not logged in we could directly open the login dialog ( A recent issue that you closed. ). Please review / merge the snackbar issue so that I can work further on this PR.

**Comment by AakashMallik** [comment]
@sk9331657 Yeah, I am little busy, I'll make the required changes in a few days.

**Comment by AakashMallik** [comment]
@anshumanv Let me know if I have missed anything out.

**Comment by AakashMallik** [comment]
@anshumanv Yup. It is a breaking change, as I have removed the reloads that happen when the person logs in. From here on, app will start to break as we will be integrating the app to the new store. I wish there was some way to work around this.

**Comment by akshatnitd** [comment]
Suggest to make a new branch from this branch and test out the complete flow. We can then move ahead with the merge and merge that PR too.

**Comment by AakashMallik** [comment]
@akshatnitd Ummm, I'll pace things up and incorporate the chnage to make it functions in this PR itself. I hope that should be okay... :innocent:

**Comment by AakashMallik** [comment]
@anshumanv It should work now. Let me know if something breaks.

NOTE: The appbar has been integrated to the store in a different PR so the Login button not chaning to Logout will be resolved in that.
Also, the login pop up won't open on other routes other than '/' as I have not passed the top level functions in those routes which will be done in this issue https://github.com/fossasia/susi_skill_cms/issues/1798. Will work on it as soon as this gets merged.

**Pull request merged**
