### PR TITLE
Change menu tabs to steps

### LINKED ISSUE #569: Make the botbuilder menu stepper
**Actual Behaviour**

The menu is of tabs as of now.
screen shot 2018-06-03 at 12 08 08 pm

**Expected Behaviour**

As it shows the process of bot creation, it should be stepwise. Something like this - 
screen shot 2018-06-03 at 12 10 50 pm

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #569 

Changes: Changed menu from tabs to steps for bot creation

Surge Deployment Link: https://pr-571-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

Step 1-
screen shot 2018-06-03 at 3 15 42 pm

Step 3-
screen shot 2018-06-03 at 3 15 56 pm

### CODE REVIEW

**Comment by DNS-404** [comment]
@akshatnitd How do I replicate this bug?

**Comment by akshatnitd** [comment]
@DNS-404 Change the screen width of your browser

**Comment by DNS-404** [comment]
Seems fine on my screen..

At approx 1400px -
screen shot 2018-06-03 at 6 17 13 pm

At approx 760px -
screen shot 2018-06-03 at 6 17 21 pm

At approx 680px -
screen shot 2018-06-03 at 6 17 27 pm

At approx 400px -
screen shot 2018-06-03 at 6 17 37 pm

**Comment by akshatnitd** [comment]
@DNS-404 You forgot to check the UI for a basic mobile viewport of width around 350 px. Please can you try opening the demo link on your mobile phone and verify.
Here is the screenshot.

**Comment by DNS-404** [comment]
@akshatnitd Okay thanks. Working on it.

**Comment by DNS-404** [comment]
@akshatnitd Fixed it 😄

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by DNS-404** [comment]
@mariobehling Done.

**Pull request merged**
