### PR TITLE
Display Skill rating in skill cards

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes issue #203 

Changes: [Add here what changes were made in this issue and if possible provide links.]
- Added skill rating on cards.

Screenshots for the change:
capture

### CODE REVIEW

**Comment by saurabhjn76** [comment]
@jajodiaraghav Thanks Please check for Travis

**Comment by jajodiaraghav** [comment]
@saurabhjn76 This is what the Travis shows:
screencapture-travis-ci-org-fossasia-susi_skill_cms-builds-295194865-1509436820644

I am not sure if this is due to my changes or there is some issue with master. Please check

**Comment by dynamitechetan** [comment]
@jajodiaraghav  the color of the like buttons is too much bright. Can you please use colors from https://material.io/guidelines/style/color.html#color-color-palette

**Comment by jajodiaraghav** [comment]
Updated:
capture

**Comment by jajodiaraghav** [comment]
@saurabhjn76 @rishiraj824 Please review and merge. Thanks

**Comment by saurabhjn76** [comment]
thanks, please also provide a surge deployment link

**Comment by jajodiaraghav** [comment]
There you go:
http://devilish-shelf.surge.sh/

I didn't knew surge is so cool for static apps :)

**Pull request merged**
