### PR TITLE
Resolve bugs in create skill - Fix #359

### LINKED ISSUE #359: Create Skill not working
**Actual Behaviour**
Reported in #358 
Create Skill not working
- It should allow any image as in the existing skills, e.g. png. So the error message itself is wrong
- It should work without an image and take a placeholder image of the system. It does neither work without adding an image.
- Also, it does not automatically insert the image url into the ::image field.
- Invalid form data is being sent

**Steps to reproduce it**
Try creating a new skill on skill cms

**Screenshots of the issue**
image

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by tstreamDOTh**
Fixes issue #359 

Changes:
- Fixed the regular expression which was causing the problem 
- Fixed the image URL in code
- Corrected the form data being sent to the server which was causing the main trouble
- Pushed the right pathnames in history props 

Surge Deployment Link: http://abundant-trees.surge.sh/

### CODE REVIEW

**Comment by tstreamDOTh** [comment]
@mariobehling Please have a look

**Comment by tstreamDOTh** [comment]
@DravitLochan These console logs were there before. Should I remove them?

**Comment by DravitLochan** [comment]
@tstreamDOTh Yes please remove them

**Comment by tstreamDOTh** [comment]
@DravitLochan Yes, removed.

**Pull request merged**
