### PR TITLE
Add support bot

### LINKED ISSUE #500: Change botbuilder to a support bot (not name, rather the functionality)
**Actual Behaviour**

Currently the botbuilder provides a bot which takes response for every query from SUSI server.

**Expected Behaviour**

It would be converted into a "contact bot" which will ask the users three questions and their answers to these questions will be stored in the server.
Relevant issue in server for this - https://github.com/fossasia/susi_server/issues/748

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #500 

Changes: Earlier I was going to replace current bot with support bot but then later on decided to add it separately.

Currently, the bot takes values from user and stores it (I'm logging it to console currently to check if the values are stored or not). Next step is to implement this on server in issue https://github.com/fossasia/susi_server/issues/748. Once it's implementation on server is done, this code can be changed accordingly. This will allow these values to be stored in server.

Surge Deployment Link: https://pr-527-fossasia-susi-skill-cms.surge.sh
For testing: Go to this link - https://dns-404.github.io/

### CODE REVIEW

**Comment by DNS-404** [comment]
@hkedia321 @anshumanv @Akshat-Jain @akshatnitd @PrP-11 Please review

**Comment by DNS-404** [comment]
@hkedia321 @akshatnitd Added email verification. Please check here - https://dns-404.github.io/

**Comment by DNS-404** [comment]
@dynamitechetan @saurabhjn76 @AliAyub007 @mariobehling Please review.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by DNS-404** [comment]
@mariobehling Done 👍

**Comment by hkedia321** [comment]
@DNS-404 there is another conflict now. Also, check the travis failure. It seems to be failing due to missing closing html tags in the `render()` method. If you will rebase to the latest commit, this should be solved automatically.

**Comment by DNS-404** [comment]
@mariobehling The reason to why i built contact bot is this -
screen shot 2018-06-03 at 11 14 42 am

So, basically this was being done because implementation of a complete bot framework takes time. Now that we're progressing in the bot framework, is this contact bot still required? and if it is, then where would it fit? Putting it on botbuilder isn't right I think.

**Comment by hkedia321** [comment]
@DNS-404 I think we should integrate this contact bot as well. People can use this pre coded contact bot instead of making their own (which is currently not possible).

**Comment by DNS-404** [comment]
🤔 Okay. This would be nice. User would have two options -
1. Either use pre-coded contact bot.
2. Or create your own bot!
Fine, thanks. I'll update this PR, resolve conflicts and squash commits.

**Comment by DNS-404** [comment]
I've created another PR for contact bot. I'm closing this one.

**Pull request closed without merging**
