### PR TITLE
Restructure menu options in botbuilder page and make responsive

### LINKED ISSUE #544: Top bar on botbuilder page should include "Deploy"
**Actual Behaviour**

"Deploy" and "Preview" buttons are separated from the top bar.

**Expected Behaviour**

These two buttons should be included in the top bar.

**Screenshots of the issue**

Current situation:
screen shot 2018-06-01 at 12 00 31 am

Desired result:
screen shot 2018-06-01 at 12 02 08 am

**Would you like to work on the issue?**

I'll be going out to station tomorrow early morning. It's a small bug. @hkedia321, you pointed it out earlier. Can you do it please?

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes #544, #549 

Changes:
- Restructure the menu options and made a column for the preview option.
- Change the colors of the menu bar.
- Make the page responsive by giving it a minimum width and enable horizontal scrolling on smaller devices.
- Removed unnecessary files like `Analytics.js` and added files for `Configure.js`, `Deploy.js`. 
- Minor bug fix in `susi-chatbot.js`.

Surge Deployment Link: https://pr-551-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
image
For mobile view:
image

### CODE REVIEW

**Comment by hkedia321** [comment]
@mariobehling I have made the required changes. Since I was waiting for PR #550 to be merged and then rebase this PR and work on top of it, I should have mentioned `WIP` on this PR. I apologize for the confusion.
I have made the menu bar similar to the mockups provided in #543. Please have a look at it here: https://pr-551-fossasia-susi-skill-cms.surge.sh/ and let me know if any more changes are required. 

Also, I will focus now on implementing features. I have already implemented the design feature in #532. I will follow on the subsequent issues related to #543 and #552. 
Thanks.

**Comment by hkedia321** [comment]
@mariobehling removed the horizontal scroll and made the card full width for the mobile view. Here is a view for a mobile device:
image
I think its working good now. Please check and let me know if any more changes are required.

**Comment by mariobehling** [comment]
Ok, thanks. The color design area should be created in a way, that a user clicks on a color box and a field expands with a color picker option. In front of the box there should be a possibility to enter a color hex code. Please implement the feature like that in follow-up issues. I am merging this for now.

**Comment by mariobehling** [comment]
Something along the lines of the following:

screenshot from 2018-06-03 02-48-42

**Pull request merged**
