### PR TITLE
Upgrade material-ui to @material-ui/core

### LINKED ISSUE #1953: Upgrade material-ui to @material-ui/core
**Actual Behaviour**

The current version of Material UI module being used for this project is now deprecated, and should be changed to @material-ui/core module.

**Expected Behaviour**

Use new module with support

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #1953 

Changes: Except Auth,Admin,Botbuilder,SkillCreator and StaticAppBar all pages are upgraded to @material-ui/core.
Surge Deployment Link: https://pr-1982-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by fragm3** [comment]
@harsh-jindal Do not update any BotBuilder or SkillCreator components, wait for https://github.com/fossasia/susi_skill_cms/pull/1978 to get merged

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review

**Comment by harsh-jindal** [comment]
@fragm3 Made the changes. Please review.

**Comment by harsh-jindal** [comment]
@fragm3 Made the changes. Please review.

**Comment by harsh-jindal** [comment]
@akshatnitd Please review.

**Pull request merged**
