### PR TITLE
Show only non empty languages

### LINKED ISSUE #1054: List only non empty languages
**Actual Behaviour**

Most of the languages do not have any skill but they are still shown in the dropdown menu.

**Expected Behaviour**

Only those languages should be shown on the category page for which skills are avaibale.

**Steps to reproduce it**

Select any language on SUSI Skill CMS other than English and Hindi. Most of them don't have a skill.

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AnupKumarPanwar**
Fixes #1054 
Merge the server side PR before it : https://github.com/fossasia/susi_server/pull/955

Changes: 
Show only those languages in the category page for which skills are available.

Surge Deployment Link: https://susi--cms.surge.sh

Screenshots for the change:
image

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
The global languages array stores the list of all the language returned from the server and languageMenuItems function fills the drop down menu with the required languages checked. 
Moreover it can be resolved in another issue as I've added few statements to the existing methodology. No new function has been created in this PR.

**Comment by AnupKumarPanwar** [comment]
@akshatnitd @stealthanthrax @PrP-11 agree?

**Comment by AnupKumarPanwar** [comment]
@Akshat-Jain @DNS-404 Please try again. Updated the surge deployment

**Comment by DNS-404** [comment]
@AnupKumarPanwar The page keeps on loading in the new deployment link.
screen shot 2018-07-15 at 11 47 31 pm

**Comment by akshatnitd** [comment]
@AnupKumarPanwar Please check, there are multiple failed requests shown on the Network tab in this deployment link.

**Comment by AnupKumarPanwar** [comment]
@akshatnitd Okay thanks for pointing out, the deployment was using my local server. Updated it please review again.

**Pull request merged**
