### PR TITLE
src: display the bot-icon uploaded with image name susi_image.jpg

### LINKED ISSUE #1602: Bot image not getting displayed
**Actual Behaviour**

If the image being uploaded for the bot has name susi_image.jpg, it is not getting displayed, instead the default susi image is displayed for the bot.

**Expected Behaviour**

The uploaded image should be displayed.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fixes #1602 

Changes: Currently if user uploads an image with name susi_image.jpg, it is not getting displayed, instead the default image is displayed, which should not be so. If the image is uploaded by the user, it should be displayed, otherwise the default image should be displayed.

Surge Deployment Link: https://pr-1607-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by AdityaSrivast** [comment]
@hkedia321 @DNS-404 Can you please review?

**Comment by AdityaSrivast** [comment]
@Akshat-Jain I changed only three files: BotBuilder.js, BotBuilderWrap.js and BotWizard.js after which I rebased

**Comment by anshumanv** [comment]
Just check the diff please.

**Comment by AdityaSrivast** [comment]
@Akshat-Jain made the changes... Can you please review again?

**Comment by AdityaSrivast** [comment]
@Akshat-Jain changes made. Can you please review?

**Pull request merged**
