### PR TITLE
Fix-1151 Make Foot Similar https://chat.susi.ai/overview

### LINKED ISSUE #1151: UI issues in sidebar and footer.
**Actual Behaviour**
* Fix divider on sidebar and remove extra border.
* Make the footer similar to https://chat.susi.ai/overview

**Would you like to work on the issue?**
Yes

### LINKED ISSUE #1152: Link skill icon to skill page and use same color for list/grid option
Sub issue of #1129 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1151 

Changes:/
Make Foot Similar https://chat.susi.ai/overview
Surge Deployment Link: https://pr-1760-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

### CODE REVIEW

**Comment by AakashMallik** [comment]
@sk9331657 The issue you are working on is a closed one. Not sure why you are working on it.

**Comment by sk9331657** [comment]
> @sk9331657 Any particular reason for having different alignments for two seemingly similar components?

It was just to make both footers look exactly same.

**Comment by sk9331657** [comment]
@samagragupta  Please check the https://chat.susi.ai/overview footer.

**Comment by sk9331657** [comment]
@DNS-404 @Akshat-Jain  @akshatnitd   Please review and guide what should be done??

**Pull request merged**
