### PR TITLE
list users page

### LINKED ISSUE #170: List all the users along with their user roles
**Expected Behaviour**
Admins should have access to list of all the users from where they can also change user role.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by DravitLochan**
fixes #170 .
Current status: "List users" option is visible to everyone but only admins can see the list when routed to /listUser. In next pr, I'll list the user role.
 added a listing page where admins can see the list of users.
to test, login to susi_server with admin email id. next login to skill_cms with same admin email id. click on list user option in top right corner. If you it is an admin session, list will be displayed otherwise "user, Not an admin will be consoled"

### CODE REVIEW

**Comment by DravitLochan** [comment]
If current user is not an admin : 
image
if current user is an admin : 
image

**Comment by mariobehling** [comment]
Please don't copy simply the code of the skills and insert users. Implement this in a way that makes sense.

Compare to existing CMS solutions. How are users displayed here?

Add a table view with the following. If this data is not yet available leave it blank for now.

| Name        | Email           | Signup      | Last Login     |  IP of Last Login  |
| ------------- |:-------------:| -------------:| -------------:|-----------------:|
| Name of User     | email@fossasia.org| 10.April 2017, 10.45AM | 27.July 2017, 09.45AM | 898.984.433 |

**Comment by DravitLochan** [comment]
@mariobehling Sure. Working on it. Will update it

**Comment by mariobehling** [comment]
@DravitLochan Please provide a screenshot for updates here.

**Comment by DravitLochan** [comment]
@mariobehling I have started the work. Expect the whole solution before noon tomorrow.

**Comment by DravitLochan** [comment]
@mariobehling I will add selectable icons as well to allow users to sort. This is just an overview
image

**Comment by DravitLochan** [comment]
@mariobehling Material UI does not have any default property to show a button in the column name. Still, will try to gather as much as I can and will try to implement it. 
no admin : 
image
admin : 
image

**Comment by mariobehling** [comment]
Thanks. I am merging this as work in progress. Please follow up on outstanding details. Cheers.

**Comment by mariobehling** [comment]
@DravitLochan When do you follow up on this? Why does the sidebar show "list users" now for anonymous users? The implementation is very buggy. Please do follow up now.

**Comment by DravitLochan** [comment]
@mariobehling Yes. Working on it!

**Pull request merged**
