### PR TITLE
Fixes #156 #149 - Added top bar and removed side bar tabs

### LINKED ISSUE #156: Simplify Skill CMS. Improve design. Delete left sidebar
Please do the following:
**Left Sidebar**
* Delete browse skills. It is not needed as the SUSI.AI logo already leads to the front page with the same content.
* Delete section and feature "Browse Examples". This should be covered by search later.
* Delete Visual Skill Editor. It is unclear what it is needed for and why it is on the sidebar.
* Delete Browse Skill Revision. It does not belong into the sidebar.

**Chat integration**
* Delete SUSI Web Chat integration. The integration is buggy and does not fulfill our needs.

**Top bar**
* Reuse the top bar from the chat page, but position the logo on the left
* Use same dropdown menu and functionality as on web chat with the tabs the same 
screenshot from 2017-07-30 00-37-25
* Delete Wikipedia message, which is there for no reason
screenshot from 2017-07-30 00-50-30

**Other**
* Add a settings page at `/settings`. This page can be blank for now. We can follow up in a separate issue.

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #156 #149 

**Changes:**

**Left Sidebar**
 - [x] Delete browse skills. It is not needed as the SUSI.AI logo already leads to the front page with the same content.
 - [x] Delete section and feature "Browse Examples". This should be covered by search later.
 - [x] Delete Visual Skill Editor. It is unclear what it is needed for and why it is on the sidebar.
 - [x] Delete Browse Skill Revision. It does not belong into the sidebar.

**Chat integration**
 - [x] Delete SUSI Web Chat integration. The integration is buggy and does not fulfill our needs.

**Top bar**
 - [x] Reuse the top bar from the chat page, but position the logo on the left
 - [x] Use same dropdown menu and functionality as on web chat with the tabs the same

 - [ ] Delete Wikipedia message, which is there for no reason - This is being implemented in https://github.com/fossasia/susi_skill_cms/issues/158

**Other**
 - [x] Add a settings page at /settings. This page can be blank for now. We can follow up in a separate issue.
 - [x] Fixed login signup button links in signup login dialogs 

**Link to deployment for testing:**  http://topbar.surge.sh/

**Screenshots for the change:** 

Top bar with drop down similar to web chat and removed redundant side bar tabs : 

topb

Empty settings page at `/settings`

topset

Removed chat integration

topchat

### CODE REVIEW

**Comment by uday96** [comment]
@saurabhjn76 @dynamitechetan @rishiraj824 @isuruAb @madhavrathi Please review

**Comment by dynamitechetan** [comment]
I think the browse Skills component link must be present in the sidebar. It is true that clicking on SUSI logo redirects to home, but users will know that.

**Comment by mariobehling** [comment]
Please delete the sidebar entirely and get rid of the browseskill. Follow the design of the chat app. Only keep the top bar in the same style as the web chat. Please help to proceed a bit faster now.

**Comment by dynamitechetan** [comment]
Okay.

**Comment by uday96** [comment]
@mariobehling Please review again - http://topbar.surge.sh/

**Comment by mariobehling** [comment]
Please use the same color for top bar and buttons as the chat app.

**Comment by uday96** [comment]
@mariobehling Done. Changed the top bar and button colors to that of chat app and used the same SUSI icon. Please check

**Comment by mariobehling** [comment]
Thanks. Please change other button colors and design following the web chat in following PRs.

**Pull request merged**
