### PR TITLE
Improve validation code on signup page

### LINKED ISSUE #1649: Improve validation code on signup page
**Actual Behaviour**

If there is an error in one field, and we start typing in other field, the error in the previous field is not displayed.

**Expected Behaviour**

If there is an error in one field, and we start typing in other field, the error in the previous field is displayed.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1649 

Changes: If there is an error in one field, and we start typing in other field, the error in the previous field is displayed.

Surge Deployment Link: https://pr-1652-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
valid-skill

### CODE REVIEW

**Comment by samagragupta** [comment]
In this should I start showing confirm password error message after minimum 6 character or not?

**Comment by Orbiter** [comment]
please resolve conflicts

**Comment by Orbiter** [comment]
@samagragupta please respond on the comment of @anshumanv as this looks to me that there is something not working

**Comment by anshumanv** [comment]
http://recordit.co/EbvyO3smdI

**Comment by samagragupta** [comment]
@Orbiter @anshumanv Done the changes

**Comment by samagragupta** [comment]
@Orbiter Please review it.

**Comment by Orbiter** [comment]
Ok @samagragupta thank you for fixing the conflicts. But now Travis is failing...

**Comment by Orbiter** [comment]
Can someone please take care of the travis message?
```

/home/travis/build/fossasia/susi_skill_cms/src/components/Auth/SignUp/SignUp.js
  213:7  error  Parsing error: Unexpected token
  211 |         break;
  212 | 
> 213 |       case 'confirmPassword':
      |       ^
  214 |         confirmPasswordValue = event.target.value;
  215 |         // let validConfirmPasswordLength = confirmPasswordValue.length >= 6;
  216 |         validPassword = confirmPasswordValue === passwordValue;
✖ 1 problem (1 error, 0 warnings)
```

**Comment by samagragupta** [comment]
@Orbiter @anshumanv Please review

**Pull request merged**
