### PR TITLE
Feat: Skill editor component is functional

### LINKED ISSUE #164: Complete the Skill Editor to upload skills to Susi Server
The skill editing component does not pushes code to the server. 
Modify it to push the skill code to the server.

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes #164
image

**Deployement Link:** http://measly-crime.surge.sh/

### CODE REVIEW

**Comment by dynamitechetan** [comment]
@saurabhjn76 @uday96 @madhavrathi  please review

**Comment by dynamitechetan** [comment]
Okay. I will make the changes.

**Comment by saurabhjn76** [comment]
@dynamitechetan Please fix the Travis build

**Comment by dynamitechetan** [comment]
@mariobheling made the changes, please review again.

**Comment by mariobehling** [comment]
@dynamitechetan Not seeing it working as expected on the test page. 

What does it mean working? Is it saved to the repository? Who can save it?

Clicking on a skill shows a different UI than clicking on the skill editor.

**Comment by dynamitechetan** [comment]
@mariobehling I am labelling this as WIP. As we discussed last night, we didn't plan to push it to skill data repository.
Now I am working on modifying API endpoints to enable pushing to skill data repository.
Clicking on a skill will show a skill description page:  https://github.com/fossasia/susi_skill_cms/pull/161
There will be an edit button on the description page which will redirect to skill editor.

**Comment by dynamitechetan** [comment]
@mariobehling The skill creating component is now functional.
**Step 1.**
Select a model, group, language and give a name to the skill. Then write the content of that skill in the editor. Click save button. A notification will come that "You skill has been uploaded"
image
**Step 2.**
To verify that skill has been uploaded. Check the browse skill component.
image

**Comment by mariobehling** [comment]
Why is the a line in the middle of the editor?

**Comment by dynamitechetan** [comment]
@mariobheling the line was a print margin, it is true by default in the editor component. I have removed it now.

**Comment by mariobehling** [comment]
* Why is there a Wikipedia info? What is this about. This is clearly a part of the skill editor page and surely should be taken out here.

**Comment by mariobehling** [comment]
* Why there is a search bar on this skill editor? Take it out.
* Why do people have to enter a name for a skill in the same area where there is search. Simplest way for the start: No need for name. It should be defined in the JSON itself for now.
* Save button should be on the bottom right.
* Add a commit message field below JSON and above search button on the bottom.

**Comment by mariobehling** [comment]
Why is there a "code" as a word in the field. There should be rather a boilerplate text similar to this one:
screenshot from 2017-08-03 08-01-25

**Comment by dynamitechetan** [comment]
> Why there is a search bar on this skill editor? Take it out.

It is a not a search bar actually. This is needed as every skill must be placed in a model, group and a language.  So we need user input here.

> Why do people have to enter a name for a skill in the same area where there is search. Simplest way for the start: No need for name. It should be defined in the JSON itself for now.

Skill name is required as the name which will be used as a file name. For example, if user gives the file name as founders so file name will be ```founders.txt```

> Save button should be on the bottom right.
> Add a commit message field below JSON and above search button on the bottom.

Done

image
Deployment link: http://majestic-produce.surge.sh

**Comment by mariobehling** [comment]
>> Why there is a search bar on this skill editor? Take it out.

> It is a not a search bar actually. This is needed as every skill must be placed in a model, group and a language.  So we need user input here.

Thank you. Please add a helper text above: "Enter skill details and placement here"

>> Why do people have to enter a name for a skill in the same area where there is search. Simplest way for the start: No need for name. It should be defined in the JSON itself for now.

> Skill name is required as the name which will be used as a file name. For example, if user gives the file name as founders so file name will be ```founders.txt```

Please take out "Skill Name" and autogenerate name of skill depending on the skill name defined in the document.

**Comment by mariobehling** [comment]
* Also add a helper text for the skill edit area: "Please fill in the skill data here."

**Comment by mariobehling** [comment]
* Ensure existing skills use the same skill editor.

**Comment by saurabhjn76** [comment]
@dynamitechetan Please fix travis

**Comment by dynamitechetan** [comment]
@mariobehling sir, As you described I removed the editor which shows on clicking of a skill.
This is the flow now.
```skill overview page -> skill info page -> edit skill page. after save -> skill info page```
When user clicks on a skill then 
image

After that, he will click on the edit button and open the editor. That editor is working fine. All changes and the commit message is pushed to the server.
image
Or If clicks the on the Create Skill button from the homepage then he is redirected to the skill editor again and he is required to fill the name, model, group and other details.
image

**Pull request merged**
