### PR TITLE
Integrate Styled components in Skill Feedback, History, Listing and RollBack

### LINKED ISSUE #2002: Integrate Styled components in Skill Feedback, History, Listing and RollBack
**Actual Behaviour**
Not present

**Expected Behaviour**
Integrate styled components

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2002 

Changes: Integrated Styled components in Skill Feedback, History, Listing and RollBack
Surge Deployment Link: https://pr-2003-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review.

**Comment by harsh-jindal** [comment]
@fragm3 Made the changes

**Comment by harsh-jindal** [comment]
> Screenshot 2019-05-29 at 12 14 21 AM
> 
> Unhide preview logo missing in demo, link: https://pr-2003-fossasia-susi-skill-cms.surge.sh/Communication/EnglishAIMLL/edit/en/51c59eb960f33ee3ee7dde10142b82ca65d54818

@fragm3 I dont understand the issue? Unhide preview logo?


> Screenshot 2019-05-29 at 12 18 34 AM
> 
> Fix this, link: https://pr-2003-fossasia-susi-skill-cms.surge.sh/Communication/EnglishAIMLL/edit/en/51c59eb960f33ee3ee7dde10142b82ca65d54818/51c59eb960f33ee3ee7dde10142b82ca65d54818
@fragm3 This page is not opening for me. Can you tell the steps to reproduce the issue?

**Comment by fragm3** [comment]
Preview window, on the left side, try hiding it and then try to make it visible again using chevron left

@harsh-jindal Yes, that's why I provided a URL for skillrollback, use that URL to go to the page

**Comment by harsh-jindal** [comment]
@fragm3 Made the changes

Screenshot 2019-05-29 at 1 08 54 PM

**Pull request merged**
