### PR TITLE
Admin Panel

### LINKED ISSUE #186: For Admin Users show menu item "Admin"
Users List was implemented in the dropdown menu for all users. It should not be there.

Please implement a menu item "Admin" below the settings item. Only show this point for admin users! Do not show this menu item for anonymous or logged in users.

On the page on the route `/admin` show tabs for `users` and `permissions` similar to this one (but using the design of the skills cms).

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes #186 After merge of this pr, Only those users with user role admin and above that will be able to access /admin route. Deployment link : http://susi-admin.surge.sh. 
image

### CODE REVIEW

**Comment by DravitLochan** [comment]
@mariobehling Please have a look at the screenshot and the deployment link.

**Comment by mariobehling** [comment]
@DravitLochan Please add a column "user roles" and show the status in that column, e.g. Admin, Confirmed, Unconfirmed

**Comment by DravitLochan** [comment]
@mariobehling For that first API end point should be modified first. As a partial fix, I request you to please merge this. I have already modified the issue https://github.com/fossasia/susi_server/issues/487 {which is to fill rest of the data in the table} for user role as well.

**Comment by DravitLochan** [comment]
@mariobehling I have added the attribute in the table. You may review it in the sample deployment link. I am working on modifying the API.

**Comment by DravitLochan** [comment]
@mariobehling Done with the user role column. I will be adding a route in accounts project where admins can change user role of other users. Please merge https://github.com/fossasia/susi_server/pull/498 before merging this pr.

**Comment by mariobehling** [comment]
@DravitLochan I am merging this as work in progress. The issue is not finished as long as the fileds don't show up completely. Please follow up on next steps. Cheers.

**Pull request merged**
