### PR TITLE
Added rendering test for SkillListing component

### LINKED ISSUE #617: Add rendering test for SkillListing component
**Actual Behaviour**

Currently, there is no rendering test for SkillListing component. All other components have a shallow rendering test.

**Expected Behaviour**

There should be a rendering test for SkillListing component also, just like the rest of the components.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #617 

Changes: Added rendering test for SkillListing component

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
@akshatnitd @anshumanv @hkedia321 @madhavrathi Can you help me with the Travis build failure please? It looks like something's wrong with the React-ace library. I've spent a lot of time on it, but I'm unable to figure it out. Can you take a look at it, please?

**Comment by Akshat-Jain** [comment]
@hkedia321 No, the test won't pass after this. That is the reason why I made a separate PR for this test. Earlier I put this test along with https://github.com/fossasia/susi_skill_cms/pull/603, but as I wasn't able to fix issues with this test, I had to remove it, because otherwise, if merged, all future PRs would face Travis failure. I've tried a lot of things to solve this, but as you said, the error is probably inside the library itself, rather than the code. Not sure how I can solve it.

**Comment by hkedia321** [comment]
Okay, then I don't think so we should merge this. The problem is somewhere inside the npm library `brace` and we can't do anything about it in this app. Maybe we can close this for now.

**Comment by anshumanv** [comment]
Does anyone here understand the use of brace?
I'm not sure what it is being used for.

**Comment by Akshat-Jain** [comment]
@hkedia321 Yes, this shouldn't be merged right now. I was just hoping if maybe it could be solved by others :sweat_smile:

**Comment by Akshat-Jain** [comment]
@akshatnitd @anshumanv @hkedia321 Closing this at the moment. I will keep on looking for the reason of the Travis failure and will proceed accordingly. Thanks :-)

**Pull request closed without merging**
