### PR TITLE
[WIP] add image upload option in botbuilder design page

### LINKED ISSUE #589: Implement a way to store images and gif for bot
**Actual Behaviour**

Currently, the user has to provide a link to the image file or gif.

**Expected Behaviour**

Providing link doesn't really make sense. User should be able to upload images.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes #589 

**Changes:**
- remove the text field for entering the URL of the image.
- add buttons for uploading image/gif for 'body background' and 'bot icon' images.
- upload the image in `imgur` API and save the link (returned from imgur API) of the image in SUSI server along with other settings in the `changeUserSettings.json` API.
- add remove icons to remove the uploaded image.
- display error messages if error occurs during fetching of settings or saving of settings.

**Surge Deployment Link:** https://pr-615-fossasia-susi-skill-cms.surge.sh

**To test:** Login and go to the `/botbuilder` design option. Upload images for the 'body background' and 'bot icon'. Then click on "Save Changes" button on the bottom of the page. Then click on "preview" button to preview your bot. The changed images should appear in the chatbot. 

 
**Screenshots for the change:**
image

### CODE REVIEW

**Comment by hkedia321** [comment]
@mariobehling Okay, I will avoid `imgur` now and store the image in SUSI server itself. Created an issue [#806](https://github.com/fossasia/susi_server/issues/806) on the server and working on it.

**Comment by hkedia321** [comment]
@mariobehling I have created a PR [#812](https://github.com/fossasia/susi_server/pull/812) on the server for this. This will store the image uploaded in the susi_skill_data repository. 
For example, an uploaded image will be available at `https://github.com/fossasia/susi_skill_data/botbuilder/harshitkedia32@gmail.com/images/logo.png`. 
I have followed the approach followed in uploading images while creating skill. 
Please confirm if this is an acceptable solution. After [#812](https://github.com/fossasia/susi_server/pull/812) is merged, I will update this PR to complete the feature.
 Also, in future maybe we can store the images in a private repo / AWS if required.

**Comment by hkedia321** [comment]
@stealthanthrax resolved conflicts.

**Comment by DNS-404** [comment]
@hkedia321 Please resolve conflicts.

**Comment by hkedia321** [comment]
closing this for now. this needs to be implemented on server first. I will update the PR accordingly.

**Comment by hkedia321** [comment]
@mariobehling I have now updated with the SUSI server's API to upload image. The image is now being stored in SUSI server. The API to fetch this saved image will be developed in [#879](https://github.com/fossasia/susi_server/issues/879). Please review. Thanks.

**Pull request closed without merging**
