### PR TITLE
Information section fixes #757

### LINKED ISSUE #757: Information Section In Skills
**Expected Behaviour**

In skills, we can add a information section, which can have:

> Last modified at - Sun, 31 Dec 2017 11:00:52 GMT
> Author: madhav rathi
> Category: Knowledge
> Language: 
> Content(Age) Rating:
> Report: Flag as inappropriate

For example: 
screen shot 2018-06-16 at 10 51 23 pm

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #757 

Changes: 
Surge Deployment Link: https://pr-757-fossasia-susi-skill-cms.surge.sh (Updated)
We need author, category, language URLs. 

Screenshots for the change:

screen shot 2018-06-17 at 4 19 59 pm

### CODE REVIEW

**Comment by fragm3** [comment]
@akshatnitd have a look at this: https://github.com/fossasia/susi_skill_cms/issues/767

**Comment by anshumanv** [comment]
Agreed with @Akshat-Jain @akshatnitd

**Comment by fragm3** [comment]
Working on route getting skills by category, language. Please see: https://github.com/fossasia/susi_skill_cms/issues/767

**Comment by fragm3** [comment]
https://github.com/fossasia/susi_skill_cms/issues/767 

Route Skills by Category and language done.

**Comment by AnupKumarPanwar** [comment]
You can use "Updated on" instead of "Last modified at".

**Comment by fragm3** [comment]
@AnupKumarPanwar we can do this later, for time being we should focus on correcting the structure.

**Comment by AnupKumarPanwar** [comment]
Resolve conflicts. Rest LGTM

**Comment by fragm3** [comment]
Okay, on it

**Comment by fragm3** [comment]
I can resolve the conflicts once the sidebar is corrected, so we have to wait!

**Comment by akshatnitd** [comment]
@fragm3 Please resolve the conflicts.

**Comment by fragm3** [comment]
Okay, working on it.

**Comment by akshatnitd** [comment]
@fragm3 Please fix the conflicts. This PR needs to be merged soon for future development

**Pull request closed without merging**
