### PR TITLE
[WIP] added skillpage for displaying skill

### PR DESCRIPTION
**Pull request by saurabhjn76**
progress for #158 

Changes: added skill page.
API integration needs to be done, working on issue https://github.com/fossasia/susi_server/issues/424
for it.
Link to deployment for testing:

Screenshots for the change: 
image

### CODE REVIEW

**Comment by mariobehling** [comment]
The data for this needs to come from the skills data repository.There is no point in hard-coding it.

Please also add an "Edit" button.

**Comment by mariobehling** [comment]
Also the images need to come from that repo. If there is not image, there should be a standard placeholder image that is coming from the CMS itself.

**Comment by saurabhjn76** [comment]
@mariobehling :+1:   yes working on it, will take care of all those things

**Comment by mariobehling** [comment]
Please follow up now. Also check travis CI. Cheers.

**Comment by saurabhjn76** [comment]
@mariobehling closing this, I have opened #179  for the same.

**Pull request closed without merging**
