### PR TITLE
Integrate Styled components and upgrade material UI in Auth Component

### LINKED ISSUE #1976: Integrate Styled components in Auth Component and upgrade material UI
**Actual Behaviour**
Currently the code is repeated several times

**Expected Behaviour**
Create a Styled component to avoid repetition of code.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #1976 

Changes: Integrated styled component in auth folder. This removes repetition of code for styles.
Surge Deployment Link: https://pr-1977-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review.

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by harsh-jindal** [comment]
@fragm3 Made the changes please review

**Comment by fragm3** [comment]
I am afraid this won't be needed now @harsh-jindal

**Comment by harsh-jindal** [comment]
@fragm3 I know as we are moving to a mono repo this will not be required. But I had made this before the meeting. But I guess as we are not abandoning the repo for now, this can be merged.

**Comment by fragm3** [comment]
@harsh-jindal One major issue with this is, we changed how Dialog used to open in chat.susi.ai. Yes, modifying skill specific stuff would be good. See this: https://github.com/fossasia/susi_skill_cms/pull/1999#pullrequestreview-242166419

**Comment by harsh-jindal** [comment]
@fragm3 Then I guess I'll close this PR.

**Pull request closed without merging**
