### PR TITLE
fixed author's url, and Placeholder image if no image is present in skill

### LINKED ISSUE #158: Implement skill page
When a user clicks on a skill e.g. on the front page, the user should first get an overview of the skill and related data. 

* Please implement an specific skill page with the basic data following the Alexa approach.
* Add a button "Edit" on the top right directing the user to the skill edit page
screenshot from 2017-07-30 01-32-19

This is related to: https://github.com/fossasia/susi_server/issues/424 and https://github.com/fossasia/susi_skill_data/issues/254

### PR DESCRIPTION
**Pull request by saurabhjn76**
fixes #158,
Changes: link to author's URL and image placeholder link.

All skills are now working, On clicking Author's name, The author's URL mentioned in skills opens up.,Also, the skill shows the placeholder image, if it is not present in skill.

Link to deployment for testing: http://susi_skill.surge.sh/

Screenshots for the change: 
image

### CODE REVIEW

**Comment by saurabhjn76** [comment]
@isuruAb done:+1: , I have fixed the GitHub URL, and placeholder image, The capitalization of author name, and image was fixed by https://github.com/fossasia/susi_server/pull/485.

**Comment by mariobehling** [comment]
If this is not up for review and merge, then please add [WIP] to your title.

**Comment by saurabhjn76** [comment]
@mariobehling it's ready for review, I have updated the comments. Capitalization of description and author's name was fixed on a server via fossasia/susi_server#485.

**Comment by mariobehling** [comment]
Thanks. Looks good. Please resolve conflicts.

**Comment by saurabhjn76** [comment]
@mariobehling done :+1:

**Pull request merged**
