### PR TITLE
Upgrade to newer React version

### LINKED ISSUE #1963: Upgrade to newer React version
**Actual Behaviour**

Currently running an older version of React

**Expected Behaviour**

Upgrade to newer react version 16.4

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #1963 
Changes: 
Upgraded react to 16.4
Upgraded react-dom to 16.4
Replaced react-diff with react-diff-viewer
Removed injectTapEventPlugin

Surge Deployment Link: https://pr-1981-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review. 
I'll create a separate PR to replace window.innerWidth in the whole repo with the util isWindow function.

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd How to fix these console errors ?
Screenshot 2019-05-16 at 1 11 06 AM

**Comment by fragm3** [comment]
@harsh-jindal try upgrading `react-router` and `react-router-dom` to a newer version

**Comment by harsh-jindal** [comment]
@akshatnitd Need help with this.
Screenshot 2019-05-16 at 6 25 53 PM

**Comment by harsh-jindal** [comment]
I tried searching it online, tried a lot of solutions but there seems to be no luck in solving this problem.

**Comment by harsh-jindal** [comment]
@akshatnitd I tried that but it didn't work.

**Comment by harsh-jindal** [comment]
@akshatnitd I had tried changing the import path in SkillVersion.js as specified in the latest version but still it didn't work.

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review.

**Pull request merged**
