### PR TITLE
Fix-1778

### LINKED ISSUE #1778: Add Option to Share Skill
**Actual Behaviour**
There is no such option to share skills.

**Expected Behaviour**
Adding Button to Share Skill

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1778 

Changes: Added Button to Share Skill on Facebook

Surge Deployment Link: https://pr-1779-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

### CODE REVIEW

**Comment by sk9331657** [comment]
@DNS-404 
@Akshat-Jain  Please review.

**Comment by AakashMallik** [comment]
@sk9331657 Please change the PR title to something more descriptive. Good practice.

**Comment by anshumanv** [comment]
Doesn't look as good to me. 😅

**Comment by sk9331657** [comment]
> Doesn't look as good to me.

What should be done to improve the pr??

**Pull request closed without merging**
