### PR TITLE
Fixes #159 - Enhance skill display

### LINKED ISSUE #159: Enhance skill display on overview page
The skills on the overview place need to have a clearer design and display info. Please compare to Alexa and follow this approach.

screenshot from 2017-07-30 00-29-03

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #159

Changes: 
- modified Cards, added information

Screenshots:-
screenshot from 2017-08-10 15 32 45
screenshot from 2017-08-10 15 33 08

Link to deployment for testing:
http://cms-skills.surge.sh

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 resolve conflicts

**Comment by mariobehling** [comment]
> Need to add relevant information

This information needs to come from the server.

**Comment by isuruAb** [comment]
@rishiraj824  please resolve conflicts

**Comment by rishiraj824** [comment]
Currently following up on the server issue https://github.com/fossasia/susi_server/issues/456 to get the meta information of the skill in the skill list.

**Comment by rishiraj824** [comment]
Please check @dynamitechetan @saurabhjn76 @uday96 @madhavrathi http://cms-skills.surge.sh/

**Comment by hpdang** [comment]
Good job! Please help to fix skills, so all displays are there properly. Cheers.

**Pull request merged**
