### PR TITLE
Make a basic builder page in botbuilder

### LINKED ISSUE #543: Create the first version of builder page for BotBuilder
**Expected Behaviour**

In the first version of builder page, bot creator would create skills that are labelled "private" the same way skills are created as of now. There won't be any pictorial representation.
These skills will be stored in susi_skill_data for now. This needs to be implemented on server as well. We need API to provide us private skill of a user(bot creator) when logged in(using `access_token`).

**Mockup**

Bot creator would be able to add multiple private skills for his/her bot which would be shown in a list. There would be a "+" button for adding new skill and after adding the skill it would be added to the list in tabular form.

List and "+" button -
screen shot 2018-05-31 at 8 37 11 pm

Creation process -
screen shot 2018-05-31 at 8 20 05 pm

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes partly #543 

Changes: 
- Added 2 options in the plus button of homepage.
- Added code view in the `build` page.
- Added "Please Login page" when the user visits the `botbuilder` page without logged in.

Surge Deployment Link: https://pr-564-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
image
image

### CODE REVIEW

**Comment by hkedia321** [comment]
@DNS-404 @PrP-11 @Akshat-Jain solved the issues. Please Review.

>"Create skill bot" should appear only when user is logged in

@DNS-404 The "Please Login" screen will appear when the user goes to the `/botbuilder` page without login, which is the same approach followed in the `/skillCreator` page. This way the user can be made known that the feature is available if they log in.

**Comment by hkedia321** [comment]
@mariobehling please review. I have tried to made it similar to the mockups provided in #543. Please let me know if any changes are required.

**Comment by mariobehling** [comment]
Please resolve merge conflicts.

**Comment by hkedia321** [comment]
@mariobehling resolved conflicts. Please review.

**Pull request merged**
