### PR TITLE
Made changes in skill rating section.

### LINKED ISSUE #618: Ratings doesn't update without page refresh
**Actual Behaviour**
Ratings doesn't update without page refresh

**Expected Behaviour**
It should update without page refresh

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

### LINKED ISSUE #637: The ratings section is a bit unclean
**Actual Behaviour**
The ratings section is a bit unclean with axes and ticks

**Expected Behaviour**
Make it as close to the screenshot

**Steps to reproduce it**
Check any skill detailed page

**Screenshots of the issue**
* Now : 

screenshot from 2018-06-09 14-31-07

* Expected :
screenshot from 2018-06-09 14-31-21

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #637 
Fixes #618 

Changes: 
* Changed UI to match that of Google Home. See screenshot.
* Made ratings updation smoother, by using response of the fiveStarRating API.

Can be merged after fossasia/susi_server#814

Surge Deployment Link: https://pr-641-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

screenshot from 2018-06-09 20-39-43

### CODE REVIEW

**Comment by akshatnitd** [comment]
@anshumanv I am aware of it. It is because if the pending PR to be merged on server. That merge will fix this.

**Comment by AnupKumarPanwar** [comment]
@akshatnitd can you give reference to that server side PR?

**Comment by akshatnitd** [comment]
@AnupKumarPanwar It is mentioned in the PR description already. Also, it has been merged.
@anshumanv The changes now work as expected. 
You can check the demo link 🙂

**Comment by mariobehling** [comment]
PLease resolve conflicts.

**Pull request merged**
