### PR TITLE
Fixes #196 Improved skill bar

### LINKED ISSUE #196: Improve skill bar
* Take out "model" and always use "general"
* Rename "Group" to "Category"
* Show full language names

screenshot from 2017-08-09 18-33-07

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes #196 

Link to deployment for testing: http://susiskillmadhav.surge.sh/

Screenshots for the change: 
new
@dynamitechetan @saurabhjn76 @mariobehling Please review
Thanks

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Should we send the list of full language names from the server?

**Comment by madhavrathi** [comment]
@mariobehling @dynamitechetan  I will remove the hard coded implementation. Please guide what to put in place of "xx". This is not a valid Language ISO code.

**Comment by madhavrathi** [comment]
@dynamitechetan @mariobehling I have removed hard coded conversion to full languages, now it is handled by an npm package: https://www.npmjs.com/package/iso-language-converter
Now I need to add a full form for "xx". Please suggest.
Thanks

**Comment by madhavrathi** [comment]
@mariobehling @dynamitechetan @saurabhjn76 Please review : http://susiskillmadhav.surge.sh/
Thanks

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
@dynamitechetan Please ensure you review changes across the app and help to get all details right.

**Comment by madhavrathi** [comment]
@mariobehling Fixed the conflicts and bar on new skill page. Please Review: http://susiskillmadhav.surge.sh/
Thanks

**Pull request merged**
