### PR TITLE
All the charts properly aligned when screen is narrowed

### LINKED ISSUE #1621: The usage chart shifts left when screen is narrowed
**Actual Behaviour**

The chart for Device wise usage shifts left when the screen is narrowed and the contents are not visible properly.

**Expected Behaviour**

The chart should move right when the screen is narrowed for proper visibility.

**Steps to reproduce it**

Choose a skill card from the main page and scroll down to the chart of Device wise usage. Narrow the screen.

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by akshi-11**
Fixes #1621 #1627 

Changes: Code added to align the device wise usage chart properly with the size of the screen.

Surge Deployment Link: https://pr-1623-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

### CODE REVIEW

**Comment by akshi-11** [comment]
@fragm3 But the charts are not aligned for cellphones. 
screenshot_2018-10-07-14-25-47-099_com android chrome

**Comment by akshi-11** [comment]
@anshumanv Okay, I'll think of something better. Thanks for the advice.

**Comment by akshi-11** [comment]
@akshatnitd Yes it is not. Thanks for noticing. I'll fix it.

**Comment by akshi-11** [comment]
I will squash the commits once they are approved.

**Comment by akshi-11** [comment]
@anshumanv please review the changes.

**Comment by mariobehling** [comment]
I am merging this as a step into the right direction. Please help to finalize this issue. Thanks!

**Pull request merged**
