### PR TITLE
Show all skills on admin dashboard

### LINKED ISSUE #987: Show all skills on dashboard of admin
**Expected Behaviour**

We need to show all skills on the dashboard of admin with an option to mark to a skill as reviewed or non-reviewed.
Issue in server: https://github.com/fossasia/susi_server/issues/933

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #987

Changes: Displaying all the skills on a new tab named `Skills` on the Admin page at `/admin` route.

**Test Link:** http://frozen-vegetable.surge.sh/. Choose `Admin` from the dropdown hamburger menu to access admin tab. (Logging in is not required)

**Note:** Action part will be implemented in the upcoming PR. It's non-functional currently.

Screenshots for the change:
screen shot 2018-07-11 at 3 55 15 pm

### CODE REVIEW

**Comment by DNS-404** [comment]
@Akshat-Jain Done. Please review.

**Comment by DNS-404** [comment]
@PrP-11 The whole project is using material-ui components. Hence, I used this UI. I think it should be changed on users tab so as to keep the design similar on the whole project. Let's see what other developers think about it. Thanks!

**Comment by akshatnitd** [comment]
@DNS-404 Can you suggest a way of testing this PR?

**Comment by PrP-11** [comment]
@DNS-404 I agree that we use most of the components from material-ui but since admin panel deals with heavy data usage therefore ant design is implemented on admin page because it is more powerful while handling table inputs.

**Comment by DNS-404** [comment]
Made the change, updated the screenshot and deployment link! @PrP-11 @Akshat-Jain @akshatnitd @anshumanv @hkedia321 Please review.

**Pull request merged**
