### PR TITLE
Fixes #903: Add SUSI icon on footer

### LINKED ISSUE #903: Make footer similar to https://chat.susi.ai/overview.
**Actual Behaviour**
* Not similar to all *.susi.ai platforms

**Expected Behaviour**
* Make footer similar to https://chat.susi.ai/overview.

**Steps to reproduce it**
* Open http://skills.susi.ai

**Screenshots of the issue**
NA

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #903

Changes: [Add here what changes were made in this issue and if possible provide links.]
* Make footer similar to https://chat.susi.ai/overview and add an icon on footer
Surge Deployment Link: https://pr-910-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
deepinscreenshot_select-area_20180701215658

### CODE REVIEW

**Comment by akshatnitd** [comment]
@Akshat-Jain @DNS-404 Made the suggested changes. Kindly check, if it looks fine now. Also, for the ordering, I am waiting for the final approval. Will make changes, as suggested by the mentors.

**Comment by akshatnitd** [comment]
* Screenshot of https://chat.susi.ai/overview
deepinscreenshot_select-area_20180701221527

**Comment by mariobehling** [comment]
Please sort menu items same as on other pages.

**Comment by akshatnitd** [comment]
@mariobehling Made changes.

**Pull request merged**
