### PR TITLE
fixed issue #1932 ( footer was not sticking at the bottom)

### LINKED ISSUE #1932: the footer is not fixed at the bottom for pages with a small height.
**Actual Behaviour**

The footer is not fixed at the bottom for pages with a small height.

**Expected Behaviour**

The footer should be fixed at the bottom.

**Steps to reproduce it**

Example page: https://skills.susi.ai/Utilities/test/en/feedbacks

**Screenshots of the issue**

issue9

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by modestlearner**
Fixes #1932

Changes: just added a css property of min-height which will push footer on pages with less content

Surge Deployment Link: https://pr-1955-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
Screenshot 2019-04-13 at 2 30 16 PM
Screenshot 2019-04-13 at 2 30 43 PM
Screenshot 2019-04-13 at 2 32 04 PM

### CODE REVIEW

**Comment by modestlearner** [comment]
Oh sorry , fixing it in a minute

**Comment by modestlearner** [comment]
I think it should be fine now.

**Comment by modestlearner** [comment]
I could have fixed the position but if I do that then on mobile displays it will be visible at the bottom on every scroll and I did not wanted to change the existing behaviour.

**Comment by modestlearner** [comment]
Yeah right seems a better approach , need to set min height for multiple viewports

**Comment by mariobehling** [comment]
Thank you for your work. Please help to finalize this PR.

**Comment by mariobehling** [comment]
Thank you for your contributions! Please open a new issue in https://github.com/fossasia/susi.ai

**Pull request closed without merging**
